// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "pkg/lib/pb/model/protos/localstore.proto" (package "anytype.model", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Relation } from "./models";
import { Struct } from "../../../../../google/protobuf/struct";
/**
 * @generated from protobuf message anytype.model.ObjectInfo
 */
export interface ObjectInfo {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: repeated string objectTypeUrls = 2
     */
    objectTypeUrls: string[]; // DEPRECATED
    /**
     * @generated from protobuf field: google.protobuf.Struct details = 3
     */
    details?: Struct;
    /**
     * @generated from protobuf field: repeated anytype.model.Relation relations = 4
     */
    relations: Relation[]; // DEPRECATED
    /**
     * @generated from protobuf field: string snippet = 5
     */
    snippet: string;
    /**
     * @generated from protobuf field: bool hasInboundLinks = 6
     */
    hasInboundLinks: boolean; // DEPRECATED
}
/**
 * @generated from protobuf message anytype.model.ObjectDetails
 */
export interface ObjectDetails {
    /**
     * @generated from protobuf field: google.protobuf.Struct details = 1
     */
    details?: Struct;
}
/**
 * @generated from protobuf message anytype.model.ObjectLinks
 */
export interface ObjectLinks {
    /**
     * @generated from protobuf field: repeated string inboundIDs = 1
     */
    inboundIDs: string[];
    /**
     * @generated from protobuf field: repeated string outboundIDs = 2
     */
    outboundIDs: string[];
}
/**
 * @generated from protobuf message anytype.model.ObjectLinksInfo
 */
export interface ObjectLinksInfo {
    /**
     * @generated from protobuf field: repeated anytype.model.ObjectInfo inbound = 1
     */
    inbound: ObjectInfo[];
    /**
     * @generated from protobuf field: repeated anytype.model.ObjectInfo outbound = 2
     */
    outbound: ObjectInfo[];
}
/**
 * @generated from protobuf message anytype.model.ObjectInfoWithLinks
 */
export interface ObjectInfoWithLinks {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: anytype.model.ObjectInfo info = 2
     */
    info?: ObjectInfo;
    /**
     * @generated from protobuf field: anytype.model.ObjectLinksInfo links = 3
     */
    links?: ObjectLinksInfo;
}
/**
 * @generated from protobuf message anytype.model.ObjectInfoWithOutboundLinks
 */
export interface ObjectInfoWithOutboundLinks {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: anytype.model.ObjectInfo info = 2
     */
    info?: ObjectInfo;
    /**
     * @generated from protobuf field: repeated anytype.model.ObjectInfo outboundLinks = 3
     */
    outboundLinks: ObjectInfo[];
}
/**
 * @generated from protobuf message anytype.model.ObjectInfoWithOutboundLinksIDs
 */
export interface ObjectInfoWithOutboundLinksIDs {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: anytype.model.ObjectInfo info = 2
     */
    info?: ObjectInfo;
    /**
     * @generated from protobuf field: repeated string outboundLinks = 3
     */
    outboundLinks: string[];
}
/**
 * @generated from protobuf message anytype.model.ObjectStoreChecksums
 */
export interface ObjectStoreChecksums {
    /**
     * @generated from protobuf field: string bundledObjectTypes = 1
     */
    bundledObjectTypes: string;
    /**
     * @generated from protobuf field: string bundledRelations = 2
     */
    bundledRelations: string;
    /**
     * @generated from protobuf field: string bundledLayouts = 3
     */
    bundledLayouts: string;
    /**
     * @generated from protobuf field: int32 objectsForceReindexCounter = 4
     */
    objectsForceReindexCounter: number; // increased in order to trigger all objects reindex
    /**
     * @generated from protobuf field: int32 filesForceReindexCounter = 5
     */
    filesForceReindexCounter: number; // increased in order to fully reindex all objects
    /**
     * @generated from protobuf field: int32 idxRebuildCounter = 6
     */
    idxRebuildCounter: number; // increased in order to remove indexes and reindex everything. Automatically triggers objects and files reindex(one time only)
    /**
     * @generated from protobuf field: int32 fulltextRebuild = 7
     */
    fulltextRebuild: number; // DEPRECATED increased in order to perform fulltext indexing for all type of objects (useful when we change fulltext config)
    /**
     * @generated from protobuf field: int32 fulltextErase = 11
     */
    fulltextErase: number; // DEPRECATED remove all the fulltext indexes and add to reindex queue after
    /**
     * @generated from protobuf field: string bundledTemplates = 8
     */
    bundledTemplates: string;
    /**
     * @generated from protobuf field: int32 bundledObjects = 9
     */
    bundledObjects: number; // anytypeProfile and maybe some others in the feature
    /**
     * @generated from protobuf field: int32 filestoreKeysForceReindexCounter = 10
     */
    filestoreKeysForceReindexCounter: number;
    /**
     * @generated from protobuf field: bool areOldFilesRemoved = 12
     */
    areOldFilesRemoved: boolean;
    /**
     * @generated from protobuf field: bool areDeletedObjectsReindexed = 13
     */
    areDeletedObjectsReindexed: boolean; // DEPRECATED
    /**
     * @generated from protobuf field: int32 linksErase = 14
     */
    linksErase: number;
    /**
     * @generated from protobuf field: int32 marketplaceForceReindexCounter = 15
     */
    marketplaceForceReindexCounter: number;
    /**
     * @generated from protobuf field: int32 reindexDeletedObjects = 16
     */
    reindexDeletedObjects: number;
    /**
     * @generated from protobuf field: int32 reindexParticipants = 17
     */
    reindexParticipants: number;
    /**
     * @generated from protobuf field: int32 reindexChats = 18
     */
    reindexChats: number;
    /**
     * @generated from protobuf field: int32 reindexFulltextChatMessages = 19
     */
    reindexFulltextChatMessages: number;
    /**
     * @generated from protobuf field: int32 invalidateObjectsIndex = 20
     */
    invalidateObjectsIndex: number;
    /**
     * @generated from protobuf field: int32 reindexDiscussions = 21
     */
    reindexDiscussions: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class ObjectInfo$Type extends MessageType<ObjectInfo> {
    constructor() {
        super("anytype.model.ObjectInfo", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "objectTypeUrls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "details", kind: "message", T: () => Struct },
            { no: 4, name: "relations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Relation },
            { no: 5, name: "snippet", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "hasInboundLinks", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ObjectInfo>): ObjectInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.objectTypeUrls = [];
        message.relations = [];
        message.snippet = "";
        message.hasInboundLinks = false;
        if (value !== undefined)
            reflectionMergePartial<ObjectInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectInfo): ObjectInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* repeated string objectTypeUrls */ 2:
                    message.objectTypeUrls.push(reader.string());
                    break;
                case /* google.protobuf.Struct details */ 3:
                    message.details = Struct.internalBinaryRead(reader, reader.uint32(), options, message.details);
                    break;
                case /* repeated anytype.model.Relation relations */ 4:
                    message.relations.push(Relation.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string snippet */ 5:
                    message.snippet = reader.string();
                    break;
                case /* bool hasInboundLinks */ 6:
                    message.hasInboundLinks = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* repeated string objectTypeUrls = 2; */
        for (let i = 0; i < message.objectTypeUrls.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.objectTypeUrls[i]);
        /* google.protobuf.Struct details = 3; */
        if (message.details)
            Struct.internalBinaryWrite(message.details, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated anytype.model.Relation relations = 4; */
        for (let i = 0; i < message.relations.length; i++)
            Relation.internalBinaryWrite(message.relations[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string snippet = 5; */
        if (message.snippet !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.snippet);
        /* bool hasInboundLinks = 6; */
        if (message.hasInboundLinks !== false)
            writer.tag(6, WireType.Varint).bool(message.hasInboundLinks);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectInfo
 */
export const ObjectInfo = new ObjectInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ObjectDetails$Type extends MessageType<ObjectDetails> {
    constructor() {
        super("anytype.model.ObjectDetails", [
            { no: 1, name: "details", kind: "message", T: () => Struct }
        ]);
    }
    create(value?: PartialMessage<ObjectDetails>): ObjectDetails {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ObjectDetails>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectDetails): ObjectDetails {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Struct details */ 1:
                    message.details = Struct.internalBinaryRead(reader, reader.uint32(), options, message.details);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectDetails, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Struct details = 1; */
        if (message.details)
            Struct.internalBinaryWrite(message.details, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectDetails
 */
export const ObjectDetails = new ObjectDetails$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ObjectLinks$Type extends MessageType<ObjectLinks> {
    constructor() {
        super("anytype.model.ObjectLinks", [
            { no: 1, name: "inboundIDs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "outboundIDs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ObjectLinks>): ObjectLinks {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.inboundIDs = [];
        message.outboundIDs = [];
        if (value !== undefined)
            reflectionMergePartial<ObjectLinks>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectLinks): ObjectLinks {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string inboundIDs */ 1:
                    message.inboundIDs.push(reader.string());
                    break;
                case /* repeated string outboundIDs */ 2:
                    message.outboundIDs.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectLinks, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string inboundIDs = 1; */
        for (let i = 0; i < message.inboundIDs.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.inboundIDs[i]);
        /* repeated string outboundIDs = 2; */
        for (let i = 0; i < message.outboundIDs.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.outboundIDs[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectLinks
 */
export const ObjectLinks = new ObjectLinks$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ObjectLinksInfo$Type extends MessageType<ObjectLinksInfo> {
    constructor() {
        super("anytype.model.ObjectLinksInfo", [
            { no: 1, name: "inbound", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ObjectInfo },
            { no: 2, name: "outbound", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ObjectInfo }
        ]);
    }
    create(value?: PartialMessage<ObjectLinksInfo>): ObjectLinksInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.inbound = [];
        message.outbound = [];
        if (value !== undefined)
            reflectionMergePartial<ObjectLinksInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectLinksInfo): ObjectLinksInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated anytype.model.ObjectInfo inbound */ 1:
                    message.inbound.push(ObjectInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated anytype.model.ObjectInfo outbound */ 2:
                    message.outbound.push(ObjectInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectLinksInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated anytype.model.ObjectInfo inbound = 1; */
        for (let i = 0; i < message.inbound.length; i++)
            ObjectInfo.internalBinaryWrite(message.inbound[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated anytype.model.ObjectInfo outbound = 2; */
        for (let i = 0; i < message.outbound.length; i++)
            ObjectInfo.internalBinaryWrite(message.outbound[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectLinksInfo
 */
export const ObjectLinksInfo = new ObjectLinksInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ObjectInfoWithLinks$Type extends MessageType<ObjectInfoWithLinks> {
    constructor() {
        super("anytype.model.ObjectInfoWithLinks", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "info", kind: "message", T: () => ObjectInfo },
            { no: 3, name: "links", kind: "message", T: () => ObjectLinksInfo }
        ]);
    }
    create(value?: PartialMessage<ObjectInfoWithLinks>): ObjectInfoWithLinks {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<ObjectInfoWithLinks>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectInfoWithLinks): ObjectInfoWithLinks {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* anytype.model.ObjectInfo info */ 2:
                    message.info = ObjectInfo.internalBinaryRead(reader, reader.uint32(), options, message.info);
                    break;
                case /* anytype.model.ObjectLinksInfo links */ 3:
                    message.links = ObjectLinksInfo.internalBinaryRead(reader, reader.uint32(), options, message.links);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectInfoWithLinks, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* anytype.model.ObjectInfo info = 2; */
        if (message.info)
            ObjectInfo.internalBinaryWrite(message.info, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* anytype.model.ObjectLinksInfo links = 3; */
        if (message.links)
            ObjectLinksInfo.internalBinaryWrite(message.links, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectInfoWithLinks
 */
export const ObjectInfoWithLinks = new ObjectInfoWithLinks$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ObjectInfoWithOutboundLinks$Type extends MessageType<ObjectInfoWithOutboundLinks> {
    constructor() {
        super("anytype.model.ObjectInfoWithOutboundLinks", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "info", kind: "message", T: () => ObjectInfo },
            { no: 3, name: "outboundLinks", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ObjectInfo }
        ]);
    }
    create(value?: PartialMessage<ObjectInfoWithOutboundLinks>): ObjectInfoWithOutboundLinks {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.outboundLinks = [];
        if (value !== undefined)
            reflectionMergePartial<ObjectInfoWithOutboundLinks>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectInfoWithOutboundLinks): ObjectInfoWithOutboundLinks {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* anytype.model.ObjectInfo info */ 2:
                    message.info = ObjectInfo.internalBinaryRead(reader, reader.uint32(), options, message.info);
                    break;
                case /* repeated anytype.model.ObjectInfo outboundLinks */ 3:
                    message.outboundLinks.push(ObjectInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectInfoWithOutboundLinks, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* anytype.model.ObjectInfo info = 2; */
        if (message.info)
            ObjectInfo.internalBinaryWrite(message.info, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated anytype.model.ObjectInfo outboundLinks = 3; */
        for (let i = 0; i < message.outboundLinks.length; i++)
            ObjectInfo.internalBinaryWrite(message.outboundLinks[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectInfoWithOutboundLinks
 */
export const ObjectInfoWithOutboundLinks = new ObjectInfoWithOutboundLinks$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ObjectInfoWithOutboundLinksIDs$Type extends MessageType<ObjectInfoWithOutboundLinksIDs> {
    constructor() {
        super("anytype.model.ObjectInfoWithOutboundLinksIDs", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "info", kind: "message", T: () => ObjectInfo },
            { no: 3, name: "outboundLinks", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ObjectInfoWithOutboundLinksIDs>): ObjectInfoWithOutboundLinksIDs {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.outboundLinks = [];
        if (value !== undefined)
            reflectionMergePartial<ObjectInfoWithOutboundLinksIDs>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectInfoWithOutboundLinksIDs): ObjectInfoWithOutboundLinksIDs {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* anytype.model.ObjectInfo info */ 2:
                    message.info = ObjectInfo.internalBinaryRead(reader, reader.uint32(), options, message.info);
                    break;
                case /* repeated string outboundLinks */ 3:
                    message.outboundLinks.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectInfoWithOutboundLinksIDs, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* anytype.model.ObjectInfo info = 2; */
        if (message.info)
            ObjectInfo.internalBinaryWrite(message.info, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string outboundLinks = 3; */
        for (let i = 0; i < message.outboundLinks.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.outboundLinks[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectInfoWithOutboundLinksIDs
 */
export const ObjectInfoWithOutboundLinksIDs = new ObjectInfoWithOutboundLinksIDs$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ObjectStoreChecksums$Type extends MessageType<ObjectStoreChecksums> {
    constructor() {
        super("anytype.model.ObjectStoreChecksums", [
            { no: 1, name: "bundledObjectTypes", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "bundledRelations", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "bundledLayouts", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "objectsForceReindexCounter", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "filesForceReindexCounter", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "idxRebuildCounter", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "fulltextRebuild", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "fulltextErase", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "bundledTemplates", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "bundledObjects", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "filestoreKeysForceReindexCounter", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "areOldFilesRemoved", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "areDeletedObjectsReindexed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 14, name: "linksErase", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 15, name: "marketplaceForceReindexCounter", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "reindexDeletedObjects", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "reindexParticipants", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 18, name: "reindexChats", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "reindexFulltextChatMessages", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 20, name: "invalidateObjectsIndex", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 21, name: "reindexDiscussions", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ObjectStoreChecksums>): ObjectStoreChecksums {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.bundledObjectTypes = "";
        message.bundledRelations = "";
        message.bundledLayouts = "";
        message.objectsForceReindexCounter = 0;
        message.filesForceReindexCounter = 0;
        message.idxRebuildCounter = 0;
        message.fulltextRebuild = 0;
        message.fulltextErase = 0;
        message.bundledTemplates = "";
        message.bundledObjects = 0;
        message.filestoreKeysForceReindexCounter = 0;
        message.areOldFilesRemoved = false;
        message.areDeletedObjectsReindexed = false;
        message.linksErase = 0;
        message.marketplaceForceReindexCounter = 0;
        message.reindexDeletedObjects = 0;
        message.reindexParticipants = 0;
        message.reindexChats = 0;
        message.reindexFulltextChatMessages = 0;
        message.invalidateObjectsIndex = 0;
        message.reindexDiscussions = 0;
        if (value !== undefined)
            reflectionMergePartial<ObjectStoreChecksums>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ObjectStoreChecksums): ObjectStoreChecksums {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string bundledObjectTypes */ 1:
                    message.bundledObjectTypes = reader.string();
                    break;
                case /* string bundledRelations */ 2:
                    message.bundledRelations = reader.string();
                    break;
                case /* string bundledLayouts */ 3:
                    message.bundledLayouts = reader.string();
                    break;
                case /* int32 objectsForceReindexCounter */ 4:
                    message.objectsForceReindexCounter = reader.int32();
                    break;
                case /* int32 filesForceReindexCounter */ 5:
                    message.filesForceReindexCounter = reader.int32();
                    break;
                case /* int32 idxRebuildCounter */ 6:
                    message.idxRebuildCounter = reader.int32();
                    break;
                case /* int32 fulltextRebuild */ 7:
                    message.fulltextRebuild = reader.int32();
                    break;
                case /* int32 fulltextErase */ 11:
                    message.fulltextErase = reader.int32();
                    break;
                case /* string bundledTemplates */ 8:
                    message.bundledTemplates = reader.string();
                    break;
                case /* int32 bundledObjects */ 9:
                    message.bundledObjects = reader.int32();
                    break;
                case /* int32 filestoreKeysForceReindexCounter */ 10:
                    message.filestoreKeysForceReindexCounter = reader.int32();
                    break;
                case /* bool areOldFilesRemoved */ 12:
                    message.areOldFilesRemoved = reader.bool();
                    break;
                case /* bool areDeletedObjectsReindexed */ 13:
                    message.areDeletedObjectsReindexed = reader.bool();
                    break;
                case /* int32 linksErase */ 14:
                    message.linksErase = reader.int32();
                    break;
                case /* int32 marketplaceForceReindexCounter */ 15:
                    message.marketplaceForceReindexCounter = reader.int32();
                    break;
                case /* int32 reindexDeletedObjects */ 16:
                    message.reindexDeletedObjects = reader.int32();
                    break;
                case /* int32 reindexParticipants */ 17:
                    message.reindexParticipants = reader.int32();
                    break;
                case /* int32 reindexChats */ 18:
                    message.reindexChats = reader.int32();
                    break;
                case /* int32 reindexFulltextChatMessages */ 19:
                    message.reindexFulltextChatMessages = reader.int32();
                    break;
                case /* int32 invalidateObjectsIndex */ 20:
                    message.invalidateObjectsIndex = reader.int32();
                    break;
                case /* int32 reindexDiscussions */ 21:
                    message.reindexDiscussions = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ObjectStoreChecksums, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string bundledObjectTypes = 1; */
        if (message.bundledObjectTypes !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.bundledObjectTypes);
        /* string bundledRelations = 2; */
        if (message.bundledRelations !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.bundledRelations);
        /* string bundledLayouts = 3; */
        if (message.bundledLayouts !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.bundledLayouts);
        /* int32 objectsForceReindexCounter = 4; */
        if (message.objectsForceReindexCounter !== 0)
            writer.tag(4, WireType.Varint).int32(message.objectsForceReindexCounter);
        /* int32 filesForceReindexCounter = 5; */
        if (message.filesForceReindexCounter !== 0)
            writer.tag(5, WireType.Varint).int32(message.filesForceReindexCounter);
        /* int32 idxRebuildCounter = 6; */
        if (message.idxRebuildCounter !== 0)
            writer.tag(6, WireType.Varint).int32(message.idxRebuildCounter);
        /* int32 fulltextRebuild = 7; */
        if (message.fulltextRebuild !== 0)
            writer.tag(7, WireType.Varint).int32(message.fulltextRebuild);
        /* string bundledTemplates = 8; */
        if (message.bundledTemplates !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.bundledTemplates);
        /* int32 bundledObjects = 9; */
        if (message.bundledObjects !== 0)
            writer.tag(9, WireType.Varint).int32(message.bundledObjects);
        /* int32 filestoreKeysForceReindexCounter = 10; */
        if (message.filestoreKeysForceReindexCounter !== 0)
            writer.tag(10, WireType.Varint).int32(message.filestoreKeysForceReindexCounter);
        /* int32 fulltextErase = 11; */
        if (message.fulltextErase !== 0)
            writer.tag(11, WireType.Varint).int32(message.fulltextErase);
        /* bool areOldFilesRemoved = 12; */
        if (message.areOldFilesRemoved !== false)
            writer.tag(12, WireType.Varint).bool(message.areOldFilesRemoved);
        /* bool areDeletedObjectsReindexed = 13; */
        if (message.areDeletedObjectsReindexed !== false)
            writer.tag(13, WireType.Varint).bool(message.areDeletedObjectsReindexed);
        /* int32 linksErase = 14; */
        if (message.linksErase !== 0)
            writer.tag(14, WireType.Varint).int32(message.linksErase);
        /* int32 marketplaceForceReindexCounter = 15; */
        if (message.marketplaceForceReindexCounter !== 0)
            writer.tag(15, WireType.Varint).int32(message.marketplaceForceReindexCounter);
        /* int32 reindexDeletedObjects = 16; */
        if (message.reindexDeletedObjects !== 0)
            writer.tag(16, WireType.Varint).int32(message.reindexDeletedObjects);
        /* int32 reindexParticipants = 17; */
        if (message.reindexParticipants !== 0)
            writer.tag(17, WireType.Varint).int32(message.reindexParticipants);
        /* int32 reindexChats = 18; */
        if (message.reindexChats !== 0)
            writer.tag(18, WireType.Varint).int32(message.reindexChats);
        /* int32 reindexFulltextChatMessages = 19; */
        if (message.reindexFulltextChatMessages !== 0)
            writer.tag(19, WireType.Varint).int32(message.reindexFulltextChatMessages);
        /* int32 invalidateObjectsIndex = 20; */
        if (message.invalidateObjectsIndex !== 0)
            writer.tag(20, WireType.Varint).int32(message.invalidateObjectsIndex);
        /* int32 reindexDiscussions = 21; */
        if (message.reindexDiscussions !== 0)
            writer.tag(21, WireType.Varint).int32(message.reindexDiscussions);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.model.ObjectStoreChecksums
 */
export const ObjectStoreChecksums = new ObjectStoreChecksums$Type();
