// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "pb/protos/service.proto" (package "anytype", syntax proto3)
// tslint:disable
import { Rpc_PushNotification_ResetIds_Response } from "./commands";
import { Rpc_PushNotification_ResetIds_Request } from "./commands";
import { Rpc_PushNotification_SetForceModeIds_Response } from "./commands";
import { Rpc_PushNotification_SetForceModeIds_Request } from "./commands";
import { Rpc_PushNotification_SetSpaceMode_Response } from "./commands";
import { Rpc_PushNotification_SetSpaceMode_Request } from "./commands";
import { Rpc_PushNotification_RegisterToken_Response } from "./commands";
import { Rpc_PushNotification_RegisterToken_Request } from "./commands";
import { Rpc_AI_ObjectCreateFromUrl_Response } from "./commands";
import { Rpc_AI_ObjectCreateFromUrl_Request } from "./commands";
import { Rpc_AI_ListSummary_Response } from "./commands";
import { Rpc_AI_ListSummary_Request } from "./commands";
import { Rpc_AI_Autofill_Response } from "./commands";
import { Rpc_AI_Autofill_Request } from "./commands";
import { Rpc_AI_WritingTools_Response } from "./commands";
import { Rpc_AI_WritingTools_Request } from "./commands";
import { Rpc_Chat_RemoveNotificationSubscriber_Response } from "./commands";
import { Rpc_Chat_RemoveNotificationSubscriber_Request } from "./commands";
import { Rpc_Chat_AddNotificationSubscriber_Response } from "./commands";
import { Rpc_Chat_AddNotificationSubscriber_Request } from "./commands";
import { Rpc_Chat_GetPinnedMessages_Response } from "./commands";
import { Rpc_Chat_GetPinnedMessages_Request } from "./commands";
import { Rpc_Chat_SetPinnedMessages_Response } from "./commands";
import { Rpc_Chat_SetPinnedMessages_Request } from "./commands";
import { Rpc_Chat_Search_Response } from "./commands";
import { Rpc_Chat_Search_Request } from "./commands";
import { Rpc_Chat_ReadReactions_Response } from "./commands";
import { Rpc_Chat_ReadReactions_Request } from "./commands";
import { Rpc_Chat_ReadAll_Response } from "./commands";
import { Rpc_Chat_ReadAll_Request } from "./commands";
import { Rpc_Object_DiscussionAdd_Response } from "./commands";
import { Rpc_Object_DiscussionAdd_Request } from "./commands";
import { Rpc_Object_ChatAdd_Response } from "./commands";
import { Rpc_Object_ChatAdd_Request } from "./commands";
import { Rpc_Chat_UnsubscribeFromMessagePreviews_Response } from "./commands";
import { Rpc_Chat_UnsubscribeFromMessagePreviews_Request } from "./commands";
import { Rpc_Chat_SubscribeToMessagePreviews_Response } from "./commands";
import { Rpc_Chat_SubscribeToMessagePreviews_Request } from "./commands";
import { Rpc_Chat_Unread_Response } from "./commands";
import { Rpc_Chat_Unread_Request } from "./commands";
import { Rpc_Chat_ReadMessages_Response } from "./commands";
import { Rpc_Chat_ReadMessages_Request } from "./commands";
import { Rpc_Chat_Unsubscribe_Response } from "./commands";
import { Rpc_Chat_Unsubscribe_Request } from "./commands";
import { Rpc_Chat_SubscribeLastMessages_Response } from "./commands";
import { Rpc_Chat_SubscribeLastMessages_Request } from "./commands";
import { Rpc_Chat_GetMessagesByIds_Response } from "./commands";
import { Rpc_Chat_GetMessagesByIds_Request } from "./commands";
import { Rpc_Chat_GetMessages_Response } from "./commands";
import { Rpc_Chat_GetMessages_Request } from "./commands";
import { Rpc_Chat_DeleteMessage_Response } from "./commands";
import { Rpc_Chat_DeleteMessage_Request } from "./commands";
import { Rpc_Chat_ToggleMessageReaction_Response } from "./commands";
import { Rpc_Chat_ToggleMessageReaction_Request } from "./commands";
import { Rpc_Chat_EditMessageContent_Response } from "./commands";
import { Rpc_Chat_EditMessageContent_Request } from "./commands";
import { Rpc_Chat_AddMessage_Response } from "./commands";
import { Rpc_Chat_AddMessage_Request } from "./commands";
import { Rpc_Device_NetworkState_Set_Response } from "./commands";
import { Rpc_Device_NetworkState_Set_Request } from "./commands";
import { Rpc_Device_List_Response } from "./commands";
import { Rpc_Device_List_Request } from "./commands";
import { Rpc_Device_SetName_Response } from "./commands";
import { Rpc_Device_SetName_Request } from "./commands";
import { Rpc_Broadcast_PayloadEvent_Response } from "./commands";
import { Rpc_Broadcast_PayloadEvent_Request } from "./commands";
import { Rpc_NameService_ResolveAnyId_Response } from "./commands";
import { Rpc_NameService_ResolveAnyId_Request } from "./commands";
import { Rpc_NameService_ResolveName_Response } from "./commands";
import { Rpc_NameService_ResolveName_Request } from "./commands";
import { Rpc_NameService_UserAccount_Get_Response } from "./commands";
import { Rpc_NameService_UserAccount_Get_Request } from "./commands";
import { Rpc_MembershipV2_SubscribeToUpdates_Response } from "./commands";
import { Rpc_MembershipV2_SubscribeToUpdates_Request } from "./commands";
import { Rpc_MembershipV2_CartUpdate_Response } from "./commands";
import { Rpc_MembershipV2_CartUpdate_Request } from "./commands";
import { Rpc_MembershipV2_CartGet_Response } from "./commands";
import { Rpc_MembershipV2_CartGet_Request } from "./commands";
import { Rpc_MembershipV2_AnyNameAllocate_Response } from "./commands";
import { Rpc_MembershipV2_AnyNameAllocate_Request } from "./commands";
import { Rpc_MembershipV2_AnyNameIsValid_Response } from "./commands";
import { Rpc_MembershipV2_AnyNameIsValid_Request } from "./commands";
import { Rpc_MembershipV2_GetPortalLink_Response } from "./commands";
import { Rpc_MembershipV2_GetPortalLink_Request } from "./commands";
import { Rpc_MembershipV2_GetStatus_Response } from "./commands";
import { Rpc_MembershipV2_GetStatus_Request } from "./commands";
import { Rpc_MembershipV2_GetProducts_Response } from "./commands";
import { Rpc_MembershipV2_GetProducts_Request } from "./commands";
import { Rpc_Membership_CodeRedeem_Response } from "./commands";
import { Rpc_Membership_CodeRedeem_Request } from "./commands";
import { Rpc_Membership_CodeGetInfo_Response } from "./commands";
import { Rpc_Membership_CodeGetInfo_Request } from "./commands";
import { Rpc_Membership_VerifyAppStoreReceipt_Response } from "./commands";
import { Rpc_Membership_VerifyAppStoreReceipt_Request } from "./commands";
import { Rpc_Membership_GetTiers_Response } from "./commands";
import { Rpc_Membership_GetTiers_Request } from "./commands";
import { Rpc_Membership_Finalize_Response } from "./commands";
import { Rpc_Membership_Finalize_Request } from "./commands";
import { Rpc_Membership_VerifyEmailCode_Response } from "./commands";
import { Rpc_Membership_VerifyEmailCode_Request } from "./commands";
import { Rpc_Membership_GetVerificationEmail_Response } from "./commands";
import { Rpc_Membership_GetVerificationEmail_Request } from "./commands";
import { Rpc_Membership_GetVerificationEmailStatus_Response } from "./commands";
import { Rpc_Membership_GetVerificationEmailStatus_Request } from "./commands";
import { Rpc_Membership_GetPortalLinkUrl_Response } from "./commands";
import { Rpc_Membership_GetPortalLinkUrl_Request } from "./commands";
import { Rpc_Membership_RegisterPaymentRequest_Response } from "./commands";
import { Rpc_Membership_RegisterPaymentRequest_Request } from "./commands";
import { Rpc_Membership_IsNameValid_Response } from "./commands";
import { Rpc_Membership_IsNameValid_Request } from "./commands";
import { Rpc_Membership_GetStatus_Response } from "./commands";
import { Rpc_Membership_GetStatus_Request } from "./commands";
import { Rpc_Notification_Test_Response } from "./commands";
import { Rpc_Notification_Test_Request } from "./commands";
import { Rpc_Notification_Reply_Response } from "./commands";
import { Rpc_Notification_Reply_Request } from "./commands";
import { Rpc_Notification_List_Response } from "./commands";
import { Rpc_Notification_List_Request } from "./commands";
import { Event } from "./events";
import { StreamRequest } from "./commands";
import { Rpc_Initial_SetParameters_Response } from "./commands";
import { Rpc_Initial_SetParameters_Request } from "./commands";
import { Rpc_Debug_CleanupReport_Response } from "./commands";
import { Rpc_Debug_CleanupReport_Request } from "./commands";
import { Rpc_Debug_ExportReport_Response } from "./commands";
import { Rpc_Debug_ExportReport_Request } from "./commands";
import { Rpc_Debug_NetCheck_Response } from "./commands";
import { Rpc_Debug_NetCheck_Request } from "./commands";
import { Rpc_Debug_AnystoreObjectChanges_Response } from "./commands";
import { Rpc_Debug_AnystoreObjectChanges_Request } from "./commands";
import { Rpc_Debug_AccountSelectTrace_Response } from "./commands";
import { Rpc_Debug_AccountSelectTrace_Request } from "./commands";
import { Rpc_Debug_RunProfiler_Response } from "./commands";
import { Rpc_Debug_RunProfiler_Request } from "./commands";
import { Rpc_Debug_OpenedObjects_Response } from "./commands";
import { Rpc_Debug_OpenedObjects_Request } from "./commands";
import { Rpc_Debug_Subscriptions_Response } from "./commands";
import { Rpc_Debug_Subscriptions_Request } from "./commands";
import { Rpc_Debug_Ping_Response } from "./commands";
import { Rpc_Debug_Ping_Request } from "./commands";
import { Rpc_Debug_ExportLocalstore_Response } from "./commands";
import { Rpc_Debug_ExportLocalstore_Request } from "./commands";
import { Rpc_Debug_StackGoroutines_Response } from "./commands";
import { Rpc_Debug_StackGoroutines_Request } from "./commands";
import { Rpc_Debug_SpaceSummary_Response } from "./commands";
import { Rpc_Debug_SpaceSummary_Request } from "./commands";
import { Rpc_Debug_TreeHeads_Response } from "./commands";
import { Rpc_Debug_TreeHeads_Request } from "./commands";
import { Rpc_Debug_Tree_Response } from "./commands";
import { Rpc_Debug_Tree_Request } from "./commands";
import { Rpc_Debug_Stat_Response } from "./commands";
import { Rpc_Debug_Stat_Request } from "./commands";
import { Rpc_Log_Send_Response } from "./commands";
import { Rpc_Log_Send_Request } from "./commands";
import { Rpc_Process_Unsubscribe_Response } from "./commands";
import { Rpc_Process_Unsubscribe_Request } from "./commands";
import { Rpc_Process_Subscribe_Response } from "./commands";
import { Rpc_Process_Subscribe_Request } from "./commands";
import { Rpc_Process_Cancel_Response } from "./commands";
import { Rpc_Process_Cancel_Request } from "./commands";
import { Rpc_BlockLatex_SetText_Response } from "./commands";
import { Rpc_BlockLatex_SetText_Request } from "./commands";
import { Rpc_BlockDiv_ListSetStyle_Response } from "./commands";
import { Rpc_BlockDiv_ListSetStyle_Request } from "./commands";
import { Rpc_BlockRelation_Add_Response } from "./commands";
import { Rpc_BlockRelation_Add_Request } from "./commands";
import { Rpc_BlockRelation_SetKey_Response } from "./commands";
import { Rpc_BlockRelation_SetKey_Request } from "./commands";
import { Rpc_BlockBookmark_CreateAndFetch_Response } from "./commands";
import { Rpc_BlockBookmark_CreateAndFetch_Request } from "./commands";
import { Rpc_BlockBookmark_Fetch_Response } from "./commands";
import { Rpc_BlockBookmark_Fetch_Request } from "./commands";
import { Rpc_BlockLink_ListSetAppearance_Response } from "./commands";
import { Rpc_BlockLink_ListSetAppearance_Request } from "./commands";
import { Rpc_BlockLink_CreateWithObject_Response } from "./commands";
import { Rpc_BlockLink_CreateWithObject_Request } from "./commands";
import { Rpc_BlockWidget_SetViewId_Response } from "./commands";
import { Rpc_BlockWidget_SetViewId_Request } from "./commands";
import { Rpc_BlockWidget_SetLimit_Response } from "./commands";
import { Rpc_BlockWidget_SetLimit_Request } from "./commands";
import { Rpc_BlockWidget_SetLayout_Response } from "./commands";
import { Rpc_BlockWidget_SetLayout_Request } from "./commands";
import { Rpc_BlockWidget_SetTargetId_Response } from "./commands";
import { Rpc_BlockWidget_SetTargetId_Request } from "./commands";
import { Rpc_Block_CreateWidget_Response } from "./commands";
import { Rpc_Block_CreateWidget_Request } from "./commands";
import { Rpc_BlockTable_Sort_Response } from "./commands";
import { Rpc_BlockTable_Sort_Request } from "./commands";
import { Rpc_BlockTable_ColumnListFill_Response } from "./commands";
import { Rpc_BlockTable_ColumnListFill_Request } from "./commands";
import { Rpc_BlockTable_RowListClean_Response } from "./commands";
import { Rpc_BlockTable_RowListClean_Request } from "./commands";
import { Rpc_BlockTable_RowListFill_Response } from "./commands";
import { Rpc_BlockTable_RowListFill_Request } from "./commands";
import { Rpc_BlockTable_ColumnDuplicate_Response } from "./commands";
import { Rpc_BlockTable_ColumnDuplicate_Request } from "./commands";
import { Rpc_BlockTable_ColumnDelete_Response } from "./commands";
import { Rpc_BlockTable_ColumnDelete_Request } from "./commands";
import { Rpc_BlockTable_ColumnMove_Response } from "./commands";
import { Rpc_BlockTable_ColumnMove_Request } from "./commands";
import { Rpc_BlockTable_ColumnCreate_Response } from "./commands";
import { Rpc_BlockTable_ColumnCreate_Request } from "./commands";
import { Rpc_BlockTable_RowSetHeader_Response } from "./commands";
import { Rpc_BlockTable_RowSetHeader_Request } from "./commands";
import { Rpc_BlockTable_RowDuplicate_Response } from "./commands";
import { Rpc_BlockTable_RowDuplicate_Request } from "./commands";
import { Rpc_BlockTable_RowDelete_Response } from "./commands";
import { Rpc_BlockTable_RowDelete_Request } from "./commands";
import { Rpc_BlockTable_RowCreate_Response } from "./commands";
import { Rpc_BlockTable_RowCreate_Request } from "./commands";
import { Rpc_BlockTable_Expand_Response } from "./commands";
import { Rpc_BlockTable_Expand_Request } from "./commands";
import { Rpc_BlockTable_Create_Response } from "./commands";
import { Rpc_BlockTable_Create_Request } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Sort_Response } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Sort_Request } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Replace_Response } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Replace_Request } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Remove_Response } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Remove_Request } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Add_Response } from "./commands";
import { Rpc_BlockDataview_ViewRelation_Add_Request } from "./commands";
import { Rpc_BlockDataview_Sort_SSort_Response } from "./commands";
import { Rpc_BlockDataview_Sort_SSort_Request } from "./commands";
import { Rpc_BlockDataview_Sort_Replace_Response } from "./commands";
import { Rpc_BlockDataview_Sort_Replace_Request } from "./commands";
import { Rpc_BlockDataview_Sort_Remove_Response } from "./commands";
import { Rpc_BlockDataview_Sort_Remove_Request } from "./commands";
import { Rpc_BlockDataview_Sort_Add_Response } from "./commands";
import { Rpc_BlockDataview_Sort_Add_Request } from "./commands";
import { Rpc_BlockDataview_Filter_Sort_Response } from "./commands";
import { Rpc_BlockDataview_Filter_Sort_Request } from "./commands";
import { Rpc_BlockDataview_Filter_Replace_Response } from "./commands";
import { Rpc_BlockDataview_Filter_Replace_Request } from "./commands";
import { Rpc_BlockDataview_Filter_Remove_Response } from "./commands";
import { Rpc_BlockDataview_Filter_Remove_Request } from "./commands";
import { Rpc_BlockDataview_Filter_Add_Response } from "./commands";
import { Rpc_BlockDataview_Filter_Add_Request } from "./commands";
import { Rpc_BlockDataview_CreateFromExistingObject_Response } from "./commands";
import { Rpc_BlockDataview_CreateFromExistingObject_Request } from "./commands";
import { Rpc_BlockDataview_ObjectOrder_Move_Response } from "./commands";
import { Rpc_BlockDataview_ObjectOrder_Move_Request } from "./commands";
import { Rpc_BlockDataview_ObjectOrder_Update_Response } from "./commands";
import { Rpc_BlockDataview_ObjectOrder_Update_Request } from "./commands";
import { Rpc_BlockDataview_GroupOrder_Update_Response } from "./commands";
import { Rpc_BlockDataview_GroupOrder_Update_Request } from "./commands";
import { Rpc_BlockDataview_Relation_Delete_Response } from "./commands";
import { Rpc_BlockDataview_Relation_Delete_Request } from "./commands";
import { Rpc_BlockDataview_Relation_Add_Response } from "./commands";
import { Rpc_BlockDataview_Relation_Add_Request } from "./commands";
import { Rpc_BlockDataview_Relation_Set_Response } from "./commands";
import { Rpc_BlockDataview_Relation_Set_Request } from "./commands";
import { Rpc_BlockDataview_SetSource_Response } from "./commands";
import { Rpc_BlockDataview_SetSource_Request } from "./commands";
import { Rpc_BlockDataview_View_SetPosition_Response } from "./commands";
import { Rpc_BlockDataview_View_SetPosition_Request } from "./commands";
import { Rpc_BlockDataview_View_SetActive_Response } from "./commands";
import { Rpc_BlockDataview_View_SetActive_Request } from "./commands";
import { Rpc_BlockDataview_View_Update_Response } from "./commands";
import { Rpc_BlockDataview_View_Update_Request } from "./commands";
import { Rpc_BlockDataview_View_Delete_Response } from "./commands";
import { Rpc_BlockDataview_View_Delete_Request } from "./commands";
import { Rpc_BlockDataview_View_Create_Response } from "./commands";
import { Rpc_BlockDataview_View_Create_Request } from "./commands";
import { Rpc_BlockFile_ListSetStyle_Response } from "./commands";
import { Rpc_BlockFile_ListSetStyle_Request } from "./commands";
import { Rpc_BlockFile_CreateAndUpload_Response } from "./commands";
import { Rpc_BlockFile_CreateAndUpload_Request } from "./commands";
import { Rpc_BlockVideo_SetName_Response } from "./commands";
import { Rpc_BlockVideo_SetName_Request } from "./commands";
import { Rpc_BlockImage_SetName_Response } from "./commands";
import { Rpc_BlockImage_SetName_Request } from "./commands";
import { Rpc_BlockFile_SetTargetObjectId_Response } from "./commands";
import { Rpc_BlockFile_SetTargetObjectId_Request } from "./commands";
import { Rpc_BlockFile_SetName_Response } from "./commands";
import { Rpc_BlockFile_SetName_Request } from "./commands";
import { Rpc_BlockText_ListClearContent_Response } from "./commands";
import { Rpc_BlockText_ListClearContent_Request } from "./commands";
import { Rpc_BlockText_ListClearStyle_Response } from "./commands";
import { Rpc_BlockText_ListClearStyle_Request } from "./commands";
import { Rpc_BlockText_ListSetStyle_Response } from "./commands";
import { Rpc_BlockText_ListSetStyle_Request } from "./commands";
import { Rpc_BlockText_ListSetMark_Response } from "./commands";
import { Rpc_BlockText_ListSetMark_Request } from "./commands";
import { Rpc_BlockText_ListSetColor_Response } from "./commands";
import { Rpc_BlockText_ListSetColor_Request } from "./commands";
import { Rpc_BlockText_SetIcon_Response } from "./commands";
import { Rpc_BlockText_SetIcon_Request } from "./commands";
import { Rpc_BlockText_SetChecked_Response } from "./commands";
import { Rpc_BlockText_SetChecked_Request } from "./commands";
import { Rpc_BlockText_SetStyle_Response } from "./commands";
import { Rpc_BlockText_SetStyle_Request } from "./commands";
import { Rpc_BlockText_SetColor_Response } from "./commands";
import { Rpc_BlockText_SetColor_Request } from "./commands";
import { Rpc_BlockText_SetText_Response } from "./commands";
import { Rpc_BlockText_SetText_Request } from "./commands";
import { Rpc_Block_ListTurnInto_Response } from "./commands";
import { Rpc_Block_ListTurnInto_Request } from "./commands";
import { Rpc_Block_ListSetVerticalAlign_Response } from "./commands";
import { Rpc_Block_ListSetVerticalAlign_Request } from "./commands";
import { Rpc_Block_ListSetAlign_Response } from "./commands";
import { Rpc_Block_ListSetAlign_Request } from "./commands";
import { Rpc_Block_ListSetBackgroundColor_Response } from "./commands";
import { Rpc_Block_ListSetBackgroundColor_Request } from "./commands";
import { Rpc_Block_ListDuplicate_Response } from "./commands";
import { Rpc_Block_ListDuplicate_Request } from "./commands";
import { Rpc_Block_ListSetFields_Response } from "./commands";
import { Rpc_Block_ListSetFields_Request } from "./commands";
import { Rpc_Block_ListConvertToObjects_Response } from "./commands";
import { Rpc_Block_ListConvertToObjects_Request } from "./commands";
import { Rpc_Block_ListMoveToNewObject_Response } from "./commands";
import { Rpc_Block_ListMoveToNewObject_Request } from "./commands";
import { Rpc_Block_ListMoveToExistingObject_Response } from "./commands";
import { Rpc_Block_ListMoveToExistingObject_Request } from "./commands";
import { Rpc_Block_ListDelete_Response } from "./commands";
import { Rpc_Block_ListDelete_Request } from "./commands";
import { Rpc_Block_Preview_Response } from "./commands";
import { Rpc_Block_Preview_Request } from "./commands";
import { Rpc_Block_SetCarriage_Response } from "./commands";
import { Rpc_Block_SetCarriage_Request } from "./commands";
import { Rpc_Block_Export_Response } from "./commands";
import { Rpc_Block_Export_Request } from "./commands";
import { Rpc_Block_SetFields_Response } from "./commands";
import { Rpc_Block_SetFields_Request } from "./commands";
import { Rpc_Block_Cut_Response } from "./commands";
import { Rpc_Block_Cut_Request } from "./commands";
import { Rpc_Block_Paste_Response } from "./commands";
import { Rpc_Block_Paste_Request } from "./commands";
import { Rpc_Block_Copy_Response } from "./commands";
import { Rpc_Block_Copy_Request } from "./commands";
import { Rpc_Block_Merge_Response } from "./commands";
import { Rpc_Block_Merge_Request } from "./commands";
import { Rpc_Block_Split_Response } from "./commands";
import { Rpc_Block_Split_Request } from "./commands";
import { Rpc_Block_Create_Response } from "./commands";
import { Rpc_Block_Create_Request } from "./commands";
import { Rpc_Block_Replace_Response } from "./commands";
import { Rpc_Block_Replace_Request } from "./commands";
import { Rpc_Block_Upload_Response } from "./commands";
import { Rpc_Block_Upload_Request } from "./commands";
import { Rpc_Gallery_DownloadIndex_Response } from "./commands";
import { Rpc_Gallery_DownloadIndex_Request } from "./commands";
import { Rpc_Gallery_DownloadManifest_Response } from "./commands";
import { Rpc_Gallery_DownloadManifest_Request } from "./commands";
import { Rpc_Unsplash_Download_Response } from "./commands";
import { Rpc_Unsplash_Download_Request } from "./commands";
import { Rpc_Unsplash_Search_Response } from "./commands";
import { Rpc_Unsplash_Search_Request } from "./commands";
import { Rpc_LinkPreview_Response } from "./commands";
import { Rpc_LinkPreview_Request } from "./commands";
import { Rpc_Template_DeletePlaceholders_Response } from "./commands";
import { Rpc_Template_DeletePlaceholders_Request } from "./commands";
import { Rpc_Template_GetPlaceholders_Response } from "./commands";
import { Rpc_Template_GetPlaceholders_Request } from "./commands";
import { Rpc_Template_SetPlaceholders_Response } from "./commands";
import { Rpc_Template_SetPlaceholders_Request } from "./commands";
import { Rpc_Template_ExportAll_Response } from "./commands";
import { Rpc_Template_ExportAll_Request } from "./commands";
import { Rpc_Template_Clone_Response } from "./commands";
import { Rpc_Template_Clone_Request } from "./commands";
import { Rpc_Template_CreateFromObject_Response } from "./commands";
import { Rpc_Template_CreateFromObject_Request } from "./commands";
import { Rpc_Navigation_GetObjectInfoWithLinks_Response } from "./commands";
import { Rpc_Navigation_GetObjectInfoWithLinks_Request } from "./commands";
import { Rpc_Navigation_ListObjects_Response } from "./commands";
import { Rpc_Navigation_ListObjects_Request } from "./commands";
import { Rpc_File_AutoDownloadSetLimit_Response } from "./commands";
import { Rpc_File_AutoDownloadSetLimit_Request } from "./commands";
import { Rpc_File_CacheCancelDownload_Response } from "./commands";
import { Rpc_File_CacheCancelDownload_Request } from "./commands";
import { Rpc_File_CacheDownload_Response } from "./commands";
import { Rpc_File_CacheDownload_Request } from "./commands";
import { Rpc_File_SetAutoDownload_Response } from "./commands";
import { Rpc_File_SetAutoDownload_Request } from "./commands";
import { Rpc_File_NodeUsage_Response } from "./commands";
import { Rpc_File_NodeUsage_Request } from "./commands";
import { Rpc_File_SpaceUsage_Response } from "./commands";
import { Rpc_File_SpaceUsage_Request } from "./commands";
import { Rpc_File_Drop_Response } from "./commands";
import { Rpc_File_Drop_Request } from "./commands";
import { Rpc_File_DiscardPreload_Response } from "./commands";
import { Rpc_File_DiscardPreload_Request } from "./commands";
import { Rpc_File_Download_Response } from "./commands";
import { Rpc_File_Download_Request } from "./commands";
import { Rpc_File_Upload_Response } from "./commands";
import { Rpc_File_Upload_Request } from "./commands";
import { Rpc_File_ListOffload_Response } from "./commands";
import { Rpc_File_ListOffload_Request } from "./commands";
import { Rpc_File_Reconcile_Response } from "./commands";
import { Rpc_File_Reconcile_Request } from "./commands";
import { Rpc_File_SpaceOffload_Response } from "./commands";
import { Rpc_File_SpaceOffload_Request } from "./commands";
import { Rpc_History_DiffVersions_Response } from "./commands";
import { Rpc_History_DiffVersions_Request } from "./commands";
import { Rpc_History_SetVersion_Response } from "./commands";
import { Rpc_History_SetVersion_Request } from "./commands";
import { Rpc_History_GetVersions_Response } from "./commands";
import { Rpc_History_GetVersions_Request } from "./commands";
import { Rpc_History_ShowVersion_Response } from "./commands";
import { Rpc_History_ShowVersion_Request } from "./commands";
import { Rpc_ObjectType_SetOrder_Response } from "./commands";
import { Rpc_ObjectType_SetOrder_Request } from "./commands";
import { Rpc_ObjectType_ResolveLayoutConflicts_Response } from "./commands";
import { Rpc_ObjectType_ResolveLayoutConflicts_Request } from "./commands";
import { Rpc_ObjectType_ListConflictingRelations_Response } from "./commands";
import { Rpc_ObjectType_ListConflictingRelations_Request } from "./commands";
import { Rpc_ObjectType_Recommended_FeaturedRelationsSet_Response } from "./commands";
import { Rpc_ObjectType_Recommended_FeaturedRelationsSet_Request } from "./commands";
import { Rpc_ObjectType_Recommended_RelationsSet_Response } from "./commands";
import { Rpc_ObjectType_Recommended_RelationsSet_Request } from "./commands";
import { Rpc_ObjectType_Relation_Remove_Response } from "./commands";
import { Rpc_ObjectType_Relation_Remove_Request } from "./commands";
import { Rpc_ObjectType_Relation_Add_Response } from "./commands";
import { Rpc_ObjectType_Relation_Add_Request } from "./commands";
import { Rpc_Object_CreateObjectType_Response } from "./commands";
import { Rpc_Object_CreateObjectType_Request } from "./commands";
import { Rpc_ObjectRelation_ListAvailable_Response } from "./commands";
import { Rpc_ObjectRelation_ListAvailable_Request } from "./commands";
import { Rpc_ObjectRelation_RemoveFeatured_Response } from "./commands";
import { Rpc_ObjectRelation_RemoveFeatured_Request } from "./commands";
import { Rpc_ObjectRelation_AddFeatured_Response } from "./commands";
import { Rpc_ObjectRelation_AddFeatured_Request } from "./commands";
import { Rpc_ObjectRelation_Delete_Response } from "./commands";
import { Rpc_ObjectRelation_Delete_Request } from "./commands";
import { Rpc_ObjectRelation_Add_Response } from "./commands";
import { Rpc_ObjectRelation_Add_Request } from "./commands";
import { Rpc_Relation_ListWithValue_Response } from "./commands";
import { Rpc_Relation_ListWithValue_Request } from "./commands";
import { Rpc_Relation_Option_SetOrder_Response } from "./commands";
import { Rpc_Relation_Option_SetOrder_Request } from "./commands";
import { Rpc_Relation_Options_Response } from "./commands";
import { Rpc_Relation_Options_Request } from "./commands";
import { Rpc_Relation_ListRemoveOption_Response } from "./commands";
import { Rpc_Relation_ListRemoveOption_Request } from "./commands";
import { Rpc_Object_CreateRelationOption_Response } from "./commands";
import { Rpc_Object_CreateRelationOption_Request } from "./commands";
import { Rpc_Object_CreateRelation_Response } from "./commands";
import { Rpc_Object_CreateRelation_Request } from "./commands";
import { Rpc_ObjectCollection_Sort_Response } from "./commands";
import { Rpc_ObjectCollection_Sort_Request } from "./commands";
import { Rpc_ObjectCollection_Remove_Response } from "./commands";
import { Rpc_ObjectCollection_Remove_Request } from "./commands";
import { Rpc_ObjectCollection_Add_Response } from "./commands";
import { Rpc_ObjectCollection_Add_Request } from "./commands";
import { Rpc_Object_DateByTimestamp_Response } from "./commands";
import { Rpc_Object_DateByTimestamp_Request } from "./commands";
import { Rpc_Object_ImportExperience_Response } from "./commands";
import { Rpc_Object_ImportExperience_Request } from "./commands";
import { Rpc_Object_ImportUseCase_Response } from "./commands";
import { Rpc_Object_ImportUseCase_Request } from "./commands";
import { Rpc_Object_Import_Notion_ValidateToken_Response } from "./commands";
import { Rpc_Object_Import_Notion_ValidateToken_Request } from "./commands";
import { Rpc_Object_ImportList_Response } from "./commands";
import { Rpc_Object_ImportList_Request } from "./commands";
import { Rpc_Object_Import_Response } from "./commands";
import { Rpc_Object_Import_Request } from "./commands";
import { Rpc_Object_BookmarkFetch_Response } from "./commands";
import { Rpc_Object_BookmarkFetch_Request } from "./commands";
import { Rpc_Object_Export_Response } from "./commands";
import { Rpc_Object_Export_Request } from "./commands";
import { Rpc_Object_ListExport_Response } from "./commands";
import { Rpc_Object_ListExport_Request } from "./commands";
import { Rpc_Object_Redo_Response } from "./commands";
import { Rpc_Object_Redo_Request } from "./commands";
import { Rpc_Object_Undo_Response } from "./commands";
import { Rpc_Object_Undo_Request } from "./commands";
import { Rpc_Object_ShareByLink_Response } from "./commands";
import { Rpc_Object_ShareByLink_Request } from "./commands";
import { Rpc_Object_ToCollection_Response } from "./commands";
import { Rpc_Object_ToCollection_Request } from "./commands";
import { Rpc_Object_ToSet_Response } from "./commands";
import { Rpc_Object_ToSet_Request } from "./commands";
import { Rpc_Object_ApplyTemplate_Response } from "./commands";
import { Rpc_Object_ApplyTemplate_Request } from "./commands";
import { Rpc_Object_ListModifyDetailValues_Response } from "./commands";
import { Rpc_Object_ListModifyDetailValues_Request } from "./commands";
import { Rpc_Object_ListSetDetails_Response } from "./commands";
import { Rpc_Object_ListSetDetails_Request } from "./commands";
import { Rpc_Object_ListSetObjectType_Response } from "./commands";
import { Rpc_Object_ListSetObjectType_Request } from "./commands";
import { Rpc_Object_ListSetIsFavorite_Response } from "./commands";
import { Rpc_Object_ListSetIsFavorite_Request } from "./commands";
import { Rpc_Object_DeletionAudit_Response } from "./commands";
import { Rpc_Object_DeletionAudit_Request } from "./commands";
import { Rpc_Object_CleanupSuggestionIgnore_Response } from "./commands";
import { Rpc_Object_CleanupSuggestionIgnore_Request } from "./commands";
import { Rpc_Object_CleanupSuggestions_Response } from "./commands";
import { Rpc_Object_CleanupSuggestions_Request } from "./commands";
import { Rpc_Object_ListSetIsArchived_Response } from "./commands";
import { Rpc_Object_ListSetIsArchived_Request } from "./commands";
import { Rpc_Object_ListDelete_Response } from "./commands";
import { Rpc_Object_ListDelete_Request } from "./commands";
import { Rpc_Object_ListDuplicate_Response } from "./commands";
import { Rpc_Object_ListDuplicate_Request } from "./commands";
import { Rpc_Object_SetSource_Response } from "./commands";
import { Rpc_Object_SetSource_Request } from "./commands";
import { Rpc_Object_SetIsArchived_Response } from "./commands";
import { Rpc_Object_SetIsArchived_Request } from "./commands";
import { Rpc_Object_SetIsFavorite_Response } from "./commands";
import { Rpc_Object_SetIsFavorite_Request } from "./commands";
import { Rpc_Object_SetInternalFlags_Response } from "./commands";
import { Rpc_Object_SetInternalFlags_Request } from "./commands";
import { Rpc_Object_SetLayout_Response } from "./commands";
import { Rpc_Object_SetLayout_Request } from "./commands";
import { Rpc_Object_SetObjectType_Response } from "./commands";
import { Rpc_Object_SetObjectType_Request } from "./commands";
import { Rpc_Object_Duplicate_Response } from "./commands";
import { Rpc_Object_Duplicate_Request } from "./commands";
import { Rpc_Object_SetDetails_Response } from "./commands";
import { Rpc_Object_SetDetails_Request } from "./commands";
import { Rpc_Object_SearchUnsubscribe_Response } from "./commands";
import { Rpc_Object_SearchUnsubscribe_Request } from "./commands";
import { Rpc_Object_GroupsSubscribe_Response } from "./commands";
import { Rpc_Object_GroupsSubscribe_Request } from "./commands";
import { Rpc_Object_SubscribeIds_Response } from "./commands";
import { Rpc_Object_SubscribeIds_Request } from "./commands";
import { Rpc_Object_CrossSpaceSearchUnsubscribe_Response } from "./commands";
import { Rpc_Object_CrossSpaceSearchUnsubscribe_Request } from "./commands";
import { Rpc_Object_CrossSpaceSearchSubscribe_Response } from "./commands";
import { Rpc_Object_CrossSpaceSearchSubscribe_Request } from "./commands";
import { Rpc_Object_SearchSubscribe_Response } from "./commands";
import { Rpc_Object_SearchSubscribe_Request } from "./commands";
import { Rpc_Object_SearchWithMeta_Response } from "./commands";
import { Rpc_Object_SearchWithMeta_Request } from "./commands";
import { Rpc_Object_Search_Response } from "./commands";
import { Rpc_Object_Search_Request } from "./commands";
import { Rpc_Object_Graph_Response } from "./commands";
import { Rpc_Object_Graph_Request } from "./commands";
import { Rpc_Object_CreateSet_Response } from "./commands";
import { Rpc_Object_CreateSet_Request } from "./commands";
import { Rpc_Object_CreateFromUrl_Response } from "./commands";
import { Rpc_Object_CreateFromUrl_Request } from "./commands";
import { Rpc_Object_CreateBookmark_Response } from "./commands";
import { Rpc_Object_CreateBookmark_Request } from "./commands";
import { Rpc_Object_Create_Response } from "./commands";
import { Rpc_Object_Create_Request } from "./commands";
import { Rpc_Object_Show_Response } from "./commands";
import { Rpc_Object_Show_Request } from "./commands";
import { Rpc_Object_Close_Response } from "./commands";
import { Rpc_Object_Close_Request } from "./commands";
import { Rpc_Object_Refresh_Response } from "./commands";
import { Rpc_Object_Refresh_Request } from "./commands";
import { Rpc_Object_Open_Response } from "./commands";
import { Rpc_Object_Open_Request } from "./commands";
import { Rpc_Publishing_GetStatus_Response } from "./commands";
import { Rpc_Publishing_GetStatus_Request } from "./commands";
import { Rpc_Publishing_ResolveUri_Response } from "./commands";
import { Rpc_Publishing_ResolveUri_Request } from "./commands";
import { Rpc_Publishing_List_Response } from "./commands";
import { Rpc_Publishing_List_Request } from "./commands";
import { Rpc_Publishing_Remove_Response } from "./commands";
import { Rpc_Publishing_Remove_Request } from "./commands";
import { Rpc_Publishing_Create_Response } from "./commands";
import { Rpc_Publishing_Create_Request } from "./commands";
import { Rpc_Space_ParticipantsAddList_Response } from "./commands";
import { Rpc_Space_ParticipantsAddList_Request } from "./commands";
import { Rpc_Space_DeleteCorruptedBackup_Response } from "./commands";
import { Rpc_Space_DeleteCorruptedBackup_Request } from "./commands";
import { Rpc_Space_ChangeOwnership_Response } from "./commands";
import { Rpc_Space_ChangeOwnership_Request } from "./commands";
import { Rpc_Space_UnsetOrder_Response } from "./commands";
import { Rpc_Space_UnsetOrder_Request } from "./commands";
import { Rpc_Space_SetOrder_Response } from "./commands";
import { Rpc_Space_SetOrder_Request } from "./commands";
import { Rpc_Space_ParticipantPermissionsChange_Response } from "./commands";
import { Rpc_Space_ParticipantPermissionsChange_Request } from "./commands";
import { Rpc_Space_ParticipantRemove_Response } from "./commands";
import { Rpc_Space_ParticipantRemove_Request } from "./commands";
import { Rpc_Space_MakeShareable_Response } from "./commands";
import { Rpc_Space_MakeShareable_Request } from "./commands";
import { Rpc_Space_LeaveApprove_Response } from "./commands";
import { Rpc_Space_LeaveApprove_Request } from "./commands";
import { Rpc_Space_RequestDecline_Response } from "./commands";
import { Rpc_Space_RequestDecline_Request } from "./commands";
import { Rpc_Space_RequestApprove_Response } from "./commands";
import { Rpc_Space_RequestApprove_Request } from "./commands";
import { Rpc_Space_StopSharing_Response } from "./commands";
import { Rpc_Space_StopSharing_Request } from "./commands";
import { Rpc_Space_JoinCancel_Response } from "./commands";
import { Rpc_Space_JoinCancel_Request } from "./commands";
import { Rpc_Space_Join_Response } from "./commands";
import { Rpc_Space_Join_Request } from "./commands";
import { Rpc_Space_InviteView_Response } from "./commands";
import { Rpc_Space_InviteView_Request } from "./commands";
import { Rpc_Space_InviteRevoke_Response } from "./commands";
import { Rpc_Space_InviteRevoke_Request } from "./commands";
import { Rpc_Space_InviteGetGuest_Response } from "./commands";
import { Rpc_Space_InviteGetGuest_Request } from "./commands";
import { Rpc_Space_InviteGetCurrent_Response } from "./commands";
import { Rpc_Space_InviteGetCurrent_Request } from "./commands";
import { Rpc_Space_InviteChange_Response } from "./commands";
import { Rpc_Space_InviteChange_Request } from "./commands";
import { Rpc_Space_InviteGenerate_Response } from "./commands";
import { Rpc_Space_InviteGenerate_Request } from "./commands";
import { Rpc_Space_Delete_Response } from "./commands";
import { Rpc_Space_Delete_Request } from "./commands";
import { Rpc_Account_ChangeNetworkConfigAndRestart_Response } from "./commands";
import { Rpc_Account_ChangeNetworkConfigAndRestart_Request } from "./commands";
import { Rpc_Account_RecoverFromLegacyExport_Response } from "./commands";
import { Rpc_Account_RecoverFromLegacyExport_Request } from "./commands";
import { Rpc_Account_ConfigUpdate_Response } from "./commands";
import { Rpc_Account_ConfigUpdate_Request } from "./commands";
import { Rpc_Account_Move_Response } from "./commands";
import { Rpc_Account_Move_Request } from "./commands";
import { Rpc_Account_Stop_Response } from "./commands";
import { Rpc_Account_Stop_Request } from "./commands";
import { Rpc_Account_ChangeJsonApiAddr_Response } from "./commands";
import { Rpc_Account_ChangeJsonApiAddr_Request } from "./commands";
import { Rpc_Account_EnableLocalNetworkSync_Response } from "./commands";
import { Rpc_Account_EnableLocalNetworkSync_Request } from "./commands";
import { Rpc_Account_Select_Response } from "./commands";
import { Rpc_Account_Select_Request } from "./commands";
import { Rpc_Account_RevertDeletion_Response } from "./commands";
import { Rpc_Account_RevertDeletion_Request } from "./commands";
import { Rpc_Account_PreloadRemainingSpaces_Response } from "./commands";
import { Rpc_Account_PreloadRemainingSpaces_Request } from "./commands";
import { Rpc_Account_Delete_Response } from "./commands";
import { Rpc_Account_Delete_Request } from "./commands";
import { Rpc_Account_Create_Response } from "./commands";
import { Rpc_Account_Create_Request } from "./commands";
import { Rpc_Account_MigrateCancel_Response } from "./commands";
import { Rpc_Account_MigrateCancel_Request } from "./commands";
import { Rpc_Account_Migrate_Response } from "./commands";
import { Rpc_Account_Migrate_Request } from "./commands";
import { Rpc_Account_Recover_Response } from "./commands";
import { Rpc_Account_Recover_Request } from "./commands";
import { Rpc_Workspace_Export_Response } from "./commands";
import { Rpc_Workspace_Export_Request } from "./commands";
import { Rpc_Workspace_SetHomepage_Response } from "./commands";
import { Rpc_Workspace_SetHomepage_Request } from "./commands";
import { Rpc_Workspace_SetInfo_Response } from "./commands";
import { Rpc_Workspace_SetInfo_Request } from "./commands";
import { Rpc_Workspace_GetAll_Response } from "./commands";
import { Rpc_Workspace_GetAll_Request } from "./commands";
import { Rpc_Workspace_GetCurrent_Response } from "./commands";
import { Rpc_Workspace_GetCurrent_Request } from "./commands";
import { Rpc_Workspace_Select_Response } from "./commands";
import { Rpc_Workspace_Select_Request } from "./commands";
import { Rpc_Workspace_Object_ListRemove_Response } from "./commands";
import { Rpc_Workspace_Object_ListRemove_Request } from "./commands";
import { Rpc_Workspace_Object_ListAdd_Response } from "./commands";
import { Rpc_Workspace_Object_ListAdd_Request } from "./commands";
import { Rpc_Workspace_Object_Add_Response } from "./commands";
import { Rpc_Workspace_Object_Add_Request } from "./commands";
import { Rpc_Workspace_Open_Response } from "./commands";
import { Rpc_Workspace_Open_Request } from "./commands";
import { Rpc_Workspace_Create_Response } from "./commands";
import { Rpc_Workspace_Create_Request } from "./commands";
import { Rpc_Wallet_CloseSession_Response } from "./commands";
import { Rpc_Wallet_CloseSession_Request } from "./commands";
import { Rpc_Wallet_CreateSession_Response } from "./commands";
import { Rpc_Wallet_CreateSession_Request } from "./commands";
import { Rpc_Account_LocalLink_RevokeApp_Response } from "./commands";
import { Rpc_Account_LocalLink_RevokeApp_Request } from "./commands";
import { Rpc_Account_LocalLink_ListApps_Response } from "./commands";
import { Rpc_Account_LocalLink_ListApps_Request } from "./commands";
import { Rpc_Account_LocalLink_CreateApp_Response } from "./commands";
import { Rpc_Account_LocalLink_CreateApp_Request } from "./commands";
import { Rpc_Account_LocalLink_SolveChallenge_Response } from "./commands";
import { Rpc_Account_LocalLink_SolveChallenge_Request } from "./commands";
import { Rpc_Account_LocalLink_NewChallenge_Response } from "./commands";
import { Rpc_Account_LocalLink_NewChallenge_Request } from "./commands";
import { Rpc_Wallet_Convert_Response } from "./commands";
import { Rpc_Wallet_Convert_Request } from "./commands";
import { Rpc_Wallet_Recover_Response } from "./commands";
import { Rpc_Wallet_Recover_Request } from "./commands";
import { Rpc_Wallet_Create_Response } from "./commands";
import { Rpc_Wallet_Create_Request } from "./commands";
import { Rpc_App_Shutdown_Response } from "./commands";
import { Rpc_App_Shutdown_Request } from "./commands";
import { Rpc_App_SetDeviceState_Response } from "./commands";
import { Rpc_App_SetDeviceState_Request } from "./commands";
import { Rpc_App_GetVersion_Response } from "./commands";
import { Rpc_App_GetVersion_Request } from "./commands";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service anytype.ClientCommands
 */
export const ClientCommands = new ServiceType("anytype.ClientCommands", [
    { name: "AppGetVersion", options: {}, I: Rpc_App_GetVersion_Request, O: Rpc_App_GetVersion_Response },
    { name: "AppSetDeviceState", options: {}, I: Rpc_App_SetDeviceState_Request, O: Rpc_App_SetDeviceState_Response },
    { name: "AppShutdown", options: {}, I: Rpc_App_Shutdown_Request, O: Rpc_App_Shutdown_Response },
    { name: "WalletCreate", options: {}, I: Rpc_Wallet_Create_Request, O: Rpc_Wallet_Create_Response },
    { name: "WalletRecover", options: {}, I: Rpc_Wallet_Recover_Request, O: Rpc_Wallet_Recover_Response },
    { name: "WalletConvert", options: {}, I: Rpc_Wallet_Convert_Request, O: Rpc_Wallet_Convert_Response },
    { name: "AccountLocalLinkNewChallenge", options: {}, I: Rpc_Account_LocalLink_NewChallenge_Request, O: Rpc_Account_LocalLink_NewChallenge_Response },
    { name: "AccountLocalLinkSolveChallenge", options: {}, I: Rpc_Account_LocalLink_SolveChallenge_Request, O: Rpc_Account_LocalLink_SolveChallenge_Response },
    { name: "AccountLocalLinkCreateApp", options: {}, I: Rpc_Account_LocalLink_CreateApp_Request, O: Rpc_Account_LocalLink_CreateApp_Response },
    { name: "AccountLocalLinkListApps", options: {}, I: Rpc_Account_LocalLink_ListApps_Request, O: Rpc_Account_LocalLink_ListApps_Response },
    { name: "AccountLocalLinkRevokeApp", options: {}, I: Rpc_Account_LocalLink_RevokeApp_Request, O: Rpc_Account_LocalLink_RevokeApp_Response },
    { name: "WalletCreateSession", options: {}, I: Rpc_Wallet_CreateSession_Request, O: Rpc_Wallet_CreateSession_Response },
    { name: "WalletCloseSession", options: {}, I: Rpc_Wallet_CloseSession_Request, O: Rpc_Wallet_CloseSession_Response },
    { name: "WorkspaceCreate", options: {}, I: Rpc_Workspace_Create_Request, O: Rpc_Workspace_Create_Response },
    { name: "WorkspaceOpen", options: {}, I: Rpc_Workspace_Open_Request, O: Rpc_Workspace_Open_Response },
    { name: "WorkspaceObjectAdd", options: {}, I: Rpc_Workspace_Object_Add_Request, O: Rpc_Workspace_Object_Add_Response },
    { name: "WorkspaceObjectListAdd", options: {}, I: Rpc_Workspace_Object_ListAdd_Request, O: Rpc_Workspace_Object_ListAdd_Response },
    { name: "WorkspaceObjectListRemove", options: {}, I: Rpc_Workspace_Object_ListRemove_Request, O: Rpc_Workspace_Object_ListRemove_Response },
    { name: "WorkspaceSelect", options: {}, I: Rpc_Workspace_Select_Request, O: Rpc_Workspace_Select_Response },
    { name: "WorkspaceGetCurrent", options: {}, I: Rpc_Workspace_GetCurrent_Request, O: Rpc_Workspace_GetCurrent_Response },
    { name: "WorkspaceGetAll", options: {}, I: Rpc_Workspace_GetAll_Request, O: Rpc_Workspace_GetAll_Response },
    { name: "WorkspaceSetInfo", options: {}, I: Rpc_Workspace_SetInfo_Request, O: Rpc_Workspace_SetInfo_Response },
    { name: "WorkspaceSetHomepage", options: {}, I: Rpc_Workspace_SetHomepage_Request, O: Rpc_Workspace_SetHomepage_Response },
    { name: "WorkspaceExport", options: {}, I: Rpc_Workspace_Export_Request, O: Rpc_Workspace_Export_Response },
    { name: "AccountRecover", options: {}, I: Rpc_Account_Recover_Request, O: Rpc_Account_Recover_Response },
    { name: "AccountMigrate", options: {}, I: Rpc_Account_Migrate_Request, O: Rpc_Account_Migrate_Response },
    { name: "AccountMigrateCancel", options: {}, I: Rpc_Account_MigrateCancel_Request, O: Rpc_Account_MigrateCancel_Response },
    { name: "AccountCreate", options: {}, I: Rpc_Account_Create_Request, O: Rpc_Account_Create_Response },
    { name: "AccountDelete", options: {}, I: Rpc_Account_Delete_Request, O: Rpc_Account_Delete_Response },
    { name: "AccountPreloadRemainingSpaces", options: {}, I: Rpc_Account_PreloadRemainingSpaces_Request, O: Rpc_Account_PreloadRemainingSpaces_Response },
    { name: "AccountRevertDeletion", options: {}, I: Rpc_Account_RevertDeletion_Request, O: Rpc_Account_RevertDeletion_Response },
    { name: "AccountSelect", options: {}, I: Rpc_Account_Select_Request, O: Rpc_Account_Select_Response },
    { name: "AccountEnableLocalNetworkSync", options: {}, I: Rpc_Account_EnableLocalNetworkSync_Request, O: Rpc_Account_EnableLocalNetworkSync_Response },
    { name: "AccountChangeJsonApiAddr", options: {}, I: Rpc_Account_ChangeJsonApiAddr_Request, O: Rpc_Account_ChangeJsonApiAddr_Response },
    { name: "AccountStop", options: {}, I: Rpc_Account_Stop_Request, O: Rpc_Account_Stop_Response },
    { name: "AccountMove", options: {}, I: Rpc_Account_Move_Request, O: Rpc_Account_Move_Response },
    { name: "AccountConfigUpdate", options: {}, I: Rpc_Account_ConfigUpdate_Request, O: Rpc_Account_ConfigUpdate_Response },
    { name: "AccountRecoverFromLegacyExport", options: {}, I: Rpc_Account_RecoverFromLegacyExport_Request, O: Rpc_Account_RecoverFromLegacyExport_Response },
    { name: "AccountChangeNetworkConfigAndRestart", options: {}, I: Rpc_Account_ChangeNetworkConfigAndRestart_Request, O: Rpc_Account_ChangeNetworkConfigAndRestart_Response },
    { name: "SpaceDelete", options: {}, I: Rpc_Space_Delete_Request, O: Rpc_Space_Delete_Response },
    { name: "SpaceInviteGenerate", options: {}, I: Rpc_Space_InviteGenerate_Request, O: Rpc_Space_InviteGenerate_Response },
    { name: "SpaceInviteChange", options: {}, I: Rpc_Space_InviteChange_Request, O: Rpc_Space_InviteChange_Response },
    { name: "SpaceInviteGetCurrent", options: {}, I: Rpc_Space_InviteGetCurrent_Request, O: Rpc_Space_InviteGetCurrent_Response },
    { name: "SpaceInviteGetGuest", options: {}, I: Rpc_Space_InviteGetGuest_Request, O: Rpc_Space_InviteGetGuest_Response },
    { name: "SpaceInviteRevoke", options: {}, I: Rpc_Space_InviteRevoke_Request, O: Rpc_Space_InviteRevoke_Response },
    { name: "SpaceInviteView", options: {}, I: Rpc_Space_InviteView_Request, O: Rpc_Space_InviteView_Response },
    { name: "SpaceJoin", options: {}, I: Rpc_Space_Join_Request, O: Rpc_Space_Join_Response },
    { name: "SpaceJoinCancel", options: {}, I: Rpc_Space_JoinCancel_Request, O: Rpc_Space_JoinCancel_Response },
    { name: "SpaceStopSharing", options: {}, I: Rpc_Space_StopSharing_Request, O: Rpc_Space_StopSharing_Response },
    { name: "SpaceRequestApprove", options: {}, I: Rpc_Space_RequestApprove_Request, O: Rpc_Space_RequestApprove_Response },
    { name: "SpaceRequestDecline", options: {}, I: Rpc_Space_RequestDecline_Request, O: Rpc_Space_RequestDecline_Response },
    { name: "SpaceLeaveApprove", options: {}, I: Rpc_Space_LeaveApprove_Request, O: Rpc_Space_LeaveApprove_Response },
    { name: "SpaceMakeShareable", options: {}, I: Rpc_Space_MakeShareable_Request, O: Rpc_Space_MakeShareable_Response },
    { name: "SpaceParticipantRemove", options: {}, I: Rpc_Space_ParticipantRemove_Request, O: Rpc_Space_ParticipantRemove_Response },
    { name: "SpaceParticipantPermissionsChange", options: {}, I: Rpc_Space_ParticipantPermissionsChange_Request, O: Rpc_Space_ParticipantPermissionsChange_Response },
    { name: "SpaceSetOrder", options: {}, I: Rpc_Space_SetOrder_Request, O: Rpc_Space_SetOrder_Response },
    { name: "SpaceUnsetOrder", options: {}, I: Rpc_Space_UnsetOrder_Request, O: Rpc_Space_UnsetOrder_Response },
    { name: "SpaceChangeOwnership", options: {}, I: Rpc_Space_ChangeOwnership_Request, O: Rpc_Space_ChangeOwnership_Response },
    { name: "SpaceDeleteCorruptedBackup", options: {}, I: Rpc_Space_DeleteCorruptedBackup_Request, O: Rpc_Space_DeleteCorruptedBackup_Response },
    { name: "SpaceParticipantsAddList", options: {}, I: Rpc_Space_ParticipantsAddList_Request, O: Rpc_Space_ParticipantsAddList_Response },
    { name: "PublishingCreate", options: {}, I: Rpc_Publishing_Create_Request, O: Rpc_Publishing_Create_Response },
    { name: "PublishingRemove", options: {}, I: Rpc_Publishing_Remove_Request, O: Rpc_Publishing_Remove_Response },
    { name: "PublishingList", options: {}, I: Rpc_Publishing_List_Request, O: Rpc_Publishing_List_Response },
    { name: "PublishingResolveUri", options: {}, I: Rpc_Publishing_ResolveUri_Request, O: Rpc_Publishing_ResolveUri_Response },
    { name: "PublishingGetStatus", options: {}, I: Rpc_Publishing_GetStatus_Request, O: Rpc_Publishing_GetStatus_Response },
    { name: "ObjectOpen", options: {}, I: Rpc_Object_Open_Request, O: Rpc_Object_Open_Response },
    { name: "ObjectRefresh", options: {}, I: Rpc_Object_Refresh_Request, O: Rpc_Object_Refresh_Response },
    { name: "ObjectClose", options: {}, I: Rpc_Object_Close_Request, O: Rpc_Object_Close_Response },
    { name: "ObjectShow", options: {}, I: Rpc_Object_Show_Request, O: Rpc_Object_Show_Response },
    { name: "ObjectCreate", options: {}, I: Rpc_Object_Create_Request, O: Rpc_Object_Create_Response },
    { name: "ObjectCreateBookmark", options: {}, I: Rpc_Object_CreateBookmark_Request, O: Rpc_Object_CreateBookmark_Response },
    { name: "ObjectCreateFromUrl", options: {}, I: Rpc_Object_CreateFromUrl_Request, O: Rpc_Object_CreateFromUrl_Response },
    { name: "ObjectCreateSet", options: {}, I: Rpc_Object_CreateSet_Request, O: Rpc_Object_CreateSet_Response },
    { name: "ObjectGraph", options: {}, I: Rpc_Object_Graph_Request, O: Rpc_Object_Graph_Response },
    { name: "ObjectSearch", options: {}, I: Rpc_Object_Search_Request, O: Rpc_Object_Search_Response },
    { name: "ObjectSearchWithMeta", options: {}, I: Rpc_Object_SearchWithMeta_Request, O: Rpc_Object_SearchWithMeta_Response },
    { name: "ObjectSearchSubscribe", options: {}, I: Rpc_Object_SearchSubscribe_Request, O: Rpc_Object_SearchSubscribe_Response },
    { name: "ObjectCrossSpaceSearchSubscribe", options: {}, I: Rpc_Object_CrossSpaceSearchSubscribe_Request, O: Rpc_Object_CrossSpaceSearchSubscribe_Response },
    { name: "ObjectCrossSpaceSearchUnsubscribe", options: {}, I: Rpc_Object_CrossSpaceSearchUnsubscribe_Request, O: Rpc_Object_CrossSpaceSearchUnsubscribe_Response },
    { name: "ObjectSubscribeIds", options: {}, I: Rpc_Object_SubscribeIds_Request, O: Rpc_Object_SubscribeIds_Response },
    { name: "ObjectGroupsSubscribe", options: {}, I: Rpc_Object_GroupsSubscribe_Request, O: Rpc_Object_GroupsSubscribe_Response },
    { name: "ObjectSearchUnsubscribe", options: {}, I: Rpc_Object_SearchUnsubscribe_Request, O: Rpc_Object_SearchUnsubscribe_Response },
    { name: "ObjectSetDetails", options: {}, I: Rpc_Object_SetDetails_Request, O: Rpc_Object_SetDetails_Response },
    { name: "ObjectDuplicate", options: {}, I: Rpc_Object_Duplicate_Request, O: Rpc_Object_Duplicate_Response },
    { name: "ObjectSetObjectType", options: {}, I: Rpc_Object_SetObjectType_Request, O: Rpc_Object_SetObjectType_Response },
    { name: "ObjectSetLayout", options: {}, I: Rpc_Object_SetLayout_Request, O: Rpc_Object_SetLayout_Response },
    { name: "ObjectSetInternalFlags", options: {}, I: Rpc_Object_SetInternalFlags_Request, O: Rpc_Object_SetInternalFlags_Response },
    { name: "ObjectSetIsFavorite", options: {}, I: Rpc_Object_SetIsFavorite_Request, O: Rpc_Object_SetIsFavorite_Response },
    { name: "ObjectSetIsArchived", options: {}, I: Rpc_Object_SetIsArchived_Request, O: Rpc_Object_SetIsArchived_Response },
    { name: "ObjectSetSource", options: {}, I: Rpc_Object_SetSource_Request, O: Rpc_Object_SetSource_Response },
    { name: "ObjectListDuplicate", options: {}, I: Rpc_Object_ListDuplicate_Request, O: Rpc_Object_ListDuplicate_Response },
    { name: "ObjectListDelete", options: {}, I: Rpc_Object_ListDelete_Request, O: Rpc_Object_ListDelete_Response },
    { name: "ObjectListSetIsArchived", options: {}, I: Rpc_Object_ListSetIsArchived_Request, O: Rpc_Object_ListSetIsArchived_Response },
    { name: "ObjectCleanupSuggestions", options: {}, I: Rpc_Object_CleanupSuggestions_Request, O: Rpc_Object_CleanupSuggestions_Response },
    { name: "ObjectCleanupSuggestionIgnore", options: {}, I: Rpc_Object_CleanupSuggestionIgnore_Request, O: Rpc_Object_CleanupSuggestionIgnore_Response },
    { name: "ObjectDeletionAudit", options: {}, I: Rpc_Object_DeletionAudit_Request, O: Rpc_Object_DeletionAudit_Response },
    { name: "ObjectListSetIsFavorite", options: {}, I: Rpc_Object_ListSetIsFavorite_Request, O: Rpc_Object_ListSetIsFavorite_Response },
    { name: "ObjectListSetObjectType", options: {}, I: Rpc_Object_ListSetObjectType_Request, O: Rpc_Object_ListSetObjectType_Response },
    { name: "ObjectListSetDetails", options: {}, I: Rpc_Object_ListSetDetails_Request, O: Rpc_Object_ListSetDetails_Response },
    { name: "ObjectListModifyDetailValues", options: {}, I: Rpc_Object_ListModifyDetailValues_Request, O: Rpc_Object_ListModifyDetailValues_Response },
    { name: "ObjectApplyTemplate", options: {}, I: Rpc_Object_ApplyTemplate_Request, O: Rpc_Object_ApplyTemplate_Response },
    { name: "ObjectToSet", options: {}, I: Rpc_Object_ToSet_Request, O: Rpc_Object_ToSet_Response },
    { name: "ObjectToCollection", options: {}, I: Rpc_Object_ToCollection_Request, O: Rpc_Object_ToCollection_Response },
    { name: "ObjectShareByLink", options: {}, I: Rpc_Object_ShareByLink_Request, O: Rpc_Object_ShareByLink_Response },
    { name: "ObjectUndo", options: {}, I: Rpc_Object_Undo_Request, O: Rpc_Object_Undo_Response },
    { name: "ObjectRedo", options: {}, I: Rpc_Object_Redo_Request, O: Rpc_Object_Redo_Response },
    { name: "ObjectListExport", options: {}, I: Rpc_Object_ListExport_Request, O: Rpc_Object_ListExport_Response },
    { name: "ObjectExport", options: {}, I: Rpc_Object_Export_Request, O: Rpc_Object_Export_Response },
    { name: "ObjectBookmarkFetch", options: {}, I: Rpc_Object_BookmarkFetch_Request, O: Rpc_Object_BookmarkFetch_Response },
    { name: "ObjectImport", options: {}, I: Rpc_Object_Import_Request, O: Rpc_Object_Import_Response },
    { name: "ObjectImportList", options: {}, I: Rpc_Object_ImportList_Request, O: Rpc_Object_ImportList_Response },
    { name: "ObjectImportNotionValidateToken", options: {}, I: Rpc_Object_Import_Notion_ValidateToken_Request, O: Rpc_Object_Import_Notion_ValidateToken_Response },
    { name: "ObjectImportUseCase", options: {}, I: Rpc_Object_ImportUseCase_Request, O: Rpc_Object_ImportUseCase_Response },
    { name: "ObjectImportExperience", options: {}, I: Rpc_Object_ImportExperience_Request, O: Rpc_Object_ImportExperience_Response },
    { name: "ObjectDateByTimestamp", options: {}, I: Rpc_Object_DateByTimestamp_Request, O: Rpc_Object_DateByTimestamp_Response },
    { name: "ObjectCollectionAdd", options: {}, I: Rpc_ObjectCollection_Add_Request, O: Rpc_ObjectCollection_Add_Response },
    { name: "ObjectCollectionRemove", options: {}, I: Rpc_ObjectCollection_Remove_Request, O: Rpc_ObjectCollection_Remove_Response },
    { name: "ObjectCollectionSort", options: {}, I: Rpc_ObjectCollection_Sort_Request, O: Rpc_ObjectCollection_Sort_Response },
    { name: "ObjectCreateRelation", options: {}, I: Rpc_Object_CreateRelation_Request, O: Rpc_Object_CreateRelation_Response },
    { name: "ObjectCreateRelationOption", options: {}, I: Rpc_Object_CreateRelationOption_Request, O: Rpc_Object_CreateRelationOption_Response },
    { name: "RelationListRemoveOption", options: {}, I: Rpc_Relation_ListRemoveOption_Request, O: Rpc_Relation_ListRemoveOption_Response },
    { name: "RelationOptions", options: {}, I: Rpc_Relation_Options_Request, O: Rpc_Relation_Options_Response },
    { name: "RelationOptionSetOrder", options: {}, I: Rpc_Relation_Option_SetOrder_Request, O: Rpc_Relation_Option_SetOrder_Response },
    { name: "RelationListWithValue", options: {}, I: Rpc_Relation_ListWithValue_Request, O: Rpc_Relation_ListWithValue_Response },
    { name: "ObjectRelationAdd", options: {}, I: Rpc_ObjectRelation_Add_Request, O: Rpc_ObjectRelation_Add_Response },
    { name: "ObjectRelationDelete", options: {}, I: Rpc_ObjectRelation_Delete_Request, O: Rpc_ObjectRelation_Delete_Response },
    { name: "ObjectRelationAddFeatured", options: {}, I: Rpc_ObjectRelation_AddFeatured_Request, O: Rpc_ObjectRelation_AddFeatured_Response },
    { name: "ObjectRelationRemoveFeatured", options: {}, I: Rpc_ObjectRelation_RemoveFeatured_Request, O: Rpc_ObjectRelation_RemoveFeatured_Response },
    { name: "ObjectRelationListAvailable", options: {}, I: Rpc_ObjectRelation_ListAvailable_Request, O: Rpc_ObjectRelation_ListAvailable_Response },
    { name: "ObjectCreateObjectType", options: {}, I: Rpc_Object_CreateObjectType_Request, O: Rpc_Object_CreateObjectType_Response },
    { name: "ObjectTypeRelationAdd", options: {}, I: Rpc_ObjectType_Relation_Add_Request, O: Rpc_ObjectType_Relation_Add_Response },
    { name: "ObjectTypeRelationRemove", options: {}, I: Rpc_ObjectType_Relation_Remove_Request, O: Rpc_ObjectType_Relation_Remove_Response },
    { name: "ObjectTypeRecommendedRelationsSet", options: {}, I: Rpc_ObjectType_Recommended_RelationsSet_Request, O: Rpc_ObjectType_Recommended_RelationsSet_Response },
    { name: "ObjectTypeRecommendedFeaturedRelationsSet", options: {}, I: Rpc_ObjectType_Recommended_FeaturedRelationsSet_Request, O: Rpc_ObjectType_Recommended_FeaturedRelationsSet_Response },
    { name: "ObjectTypeListConflictingRelations", options: {}, I: Rpc_ObjectType_ListConflictingRelations_Request, O: Rpc_ObjectType_ListConflictingRelations_Response },
    { name: "ObjectTypeResolveLayoutConflicts", options: {}, I: Rpc_ObjectType_ResolveLayoutConflicts_Request, O: Rpc_ObjectType_ResolveLayoutConflicts_Response },
    { name: "ObjectTypeSetOrder", options: {}, I: Rpc_ObjectType_SetOrder_Request, O: Rpc_ObjectType_SetOrder_Response },
    { name: "HistoryShowVersion", options: {}, I: Rpc_History_ShowVersion_Request, O: Rpc_History_ShowVersion_Response },
    { name: "HistoryGetVersions", options: {}, I: Rpc_History_GetVersions_Request, O: Rpc_History_GetVersions_Response },
    { name: "HistorySetVersion", options: {}, I: Rpc_History_SetVersion_Request, O: Rpc_History_SetVersion_Response },
    { name: "HistoryDiffVersions", options: {}, I: Rpc_History_DiffVersions_Request, O: Rpc_History_DiffVersions_Response },
    { name: "FileSpaceOffload", options: {}, I: Rpc_File_SpaceOffload_Request, O: Rpc_File_SpaceOffload_Response },
    { name: "FileReconcile", options: {}, I: Rpc_File_Reconcile_Request, O: Rpc_File_Reconcile_Response },
    { name: "FileListOffload", options: {}, I: Rpc_File_ListOffload_Request, O: Rpc_File_ListOffload_Response },
    { name: "FileUpload", options: {}, I: Rpc_File_Upload_Request, O: Rpc_File_Upload_Response },
    { name: "FileDownload", options: {}, I: Rpc_File_Download_Request, O: Rpc_File_Download_Response },
    { name: "FileDiscardPreload", options: {}, I: Rpc_File_DiscardPreload_Request, O: Rpc_File_DiscardPreload_Response },
    { name: "FileDrop", options: {}, I: Rpc_File_Drop_Request, O: Rpc_File_Drop_Response },
    { name: "FileSpaceUsage", options: {}, I: Rpc_File_SpaceUsage_Request, O: Rpc_File_SpaceUsage_Response },
    { name: "FileNodeUsage", options: {}, I: Rpc_File_NodeUsage_Request, O: Rpc_File_NodeUsage_Response },
    { name: "FileSetAutoDownload", options: {}, I: Rpc_File_SetAutoDownload_Request, O: Rpc_File_SetAutoDownload_Response },
    { name: "FileCacheDownload", options: {}, I: Rpc_File_CacheDownload_Request, O: Rpc_File_CacheDownload_Response },
    { name: "FileCacheCancelDownload", options: {}, I: Rpc_File_CacheCancelDownload_Request, O: Rpc_File_CacheCancelDownload_Response },
    { name: "FileAutoDownloadSetLimit", options: {}, I: Rpc_File_AutoDownloadSetLimit_Request, O: Rpc_File_AutoDownloadSetLimit_Response },
    { name: "NavigationListObjects", options: {}, I: Rpc_Navigation_ListObjects_Request, O: Rpc_Navigation_ListObjects_Response },
    { name: "NavigationGetObjectInfoWithLinks", options: {}, I: Rpc_Navigation_GetObjectInfoWithLinks_Request, O: Rpc_Navigation_GetObjectInfoWithLinks_Response },
    { name: "TemplateCreateFromObject", options: {}, I: Rpc_Template_CreateFromObject_Request, O: Rpc_Template_CreateFromObject_Response },
    { name: "TemplateClone", options: {}, I: Rpc_Template_Clone_Request, O: Rpc_Template_Clone_Response },
    { name: "TemplateExportAll", options: {}, I: Rpc_Template_ExportAll_Request, O: Rpc_Template_ExportAll_Response },
    { name: "TemplateSetPlaceholders", options: {}, I: Rpc_Template_SetPlaceholders_Request, O: Rpc_Template_SetPlaceholders_Response },
    { name: "TemplateGetPlaceholders", options: {}, I: Rpc_Template_GetPlaceholders_Request, O: Rpc_Template_GetPlaceholders_Response },
    { name: "TemplateDeletePlaceholders", options: {}, I: Rpc_Template_DeletePlaceholders_Request, O: Rpc_Template_DeletePlaceholders_Response },
    { name: "LinkPreview", options: {}, I: Rpc_LinkPreview_Request, O: Rpc_LinkPreview_Response },
    { name: "UnsplashSearch", options: {}, I: Rpc_Unsplash_Search_Request, O: Rpc_Unsplash_Search_Response },
    { name: "UnsplashDownload", options: {}, I: Rpc_Unsplash_Download_Request, O: Rpc_Unsplash_Download_Response },
    { name: "GalleryDownloadManifest", options: {}, I: Rpc_Gallery_DownloadManifest_Request, O: Rpc_Gallery_DownloadManifest_Response },
    { name: "GalleryDownloadIndex", options: {}, I: Rpc_Gallery_DownloadIndex_Request, O: Rpc_Gallery_DownloadIndex_Response },
    { name: "BlockUpload", options: {}, I: Rpc_Block_Upload_Request, O: Rpc_Block_Upload_Response },
    { name: "BlockReplace", options: {}, I: Rpc_Block_Replace_Request, O: Rpc_Block_Replace_Response },
    { name: "BlockCreate", options: {}, I: Rpc_Block_Create_Request, O: Rpc_Block_Create_Response },
    { name: "BlockSplit", options: {}, I: Rpc_Block_Split_Request, O: Rpc_Block_Split_Response },
    { name: "BlockMerge", options: {}, I: Rpc_Block_Merge_Request, O: Rpc_Block_Merge_Response },
    { name: "BlockCopy", options: {}, I: Rpc_Block_Copy_Request, O: Rpc_Block_Copy_Response },
    { name: "BlockPaste", options: {}, I: Rpc_Block_Paste_Request, O: Rpc_Block_Paste_Response },
    { name: "BlockCut", options: {}, I: Rpc_Block_Cut_Request, O: Rpc_Block_Cut_Response },
    { name: "BlockSetFields", options: {}, I: Rpc_Block_SetFields_Request, O: Rpc_Block_SetFields_Response },
    { name: "BlockExport", options: {}, I: Rpc_Block_Export_Request, O: Rpc_Block_Export_Response },
    { name: "BlockSetCarriage", options: {}, I: Rpc_Block_SetCarriage_Request, O: Rpc_Block_SetCarriage_Response },
    { name: "BlockPreview", options: {}, I: Rpc_Block_Preview_Request, O: Rpc_Block_Preview_Response },
    { name: "BlockListDelete", options: {}, I: Rpc_Block_ListDelete_Request, O: Rpc_Block_ListDelete_Response },
    { name: "BlockListMoveToExistingObject", options: {}, I: Rpc_Block_ListMoveToExistingObject_Request, O: Rpc_Block_ListMoveToExistingObject_Response },
    { name: "BlockListMoveToNewObject", options: {}, I: Rpc_Block_ListMoveToNewObject_Request, O: Rpc_Block_ListMoveToNewObject_Response },
    { name: "BlockListConvertToObjects", options: {}, I: Rpc_Block_ListConvertToObjects_Request, O: Rpc_Block_ListConvertToObjects_Response },
    { name: "BlockListSetFields", options: {}, I: Rpc_Block_ListSetFields_Request, O: Rpc_Block_ListSetFields_Response },
    { name: "BlockListDuplicate", options: {}, I: Rpc_Block_ListDuplicate_Request, O: Rpc_Block_ListDuplicate_Response },
    { name: "BlockListSetBackgroundColor", options: {}, I: Rpc_Block_ListSetBackgroundColor_Request, O: Rpc_Block_ListSetBackgroundColor_Response },
    { name: "BlockListSetAlign", options: {}, I: Rpc_Block_ListSetAlign_Request, O: Rpc_Block_ListSetAlign_Response },
    { name: "BlockListSetVerticalAlign", options: {}, I: Rpc_Block_ListSetVerticalAlign_Request, O: Rpc_Block_ListSetVerticalAlign_Response },
    { name: "BlockListTurnInto", options: {}, I: Rpc_Block_ListTurnInto_Request, O: Rpc_Block_ListTurnInto_Response },
    { name: "BlockTextSetText", options: {}, I: Rpc_BlockText_SetText_Request, O: Rpc_BlockText_SetText_Response },
    { name: "BlockTextSetColor", options: {}, I: Rpc_BlockText_SetColor_Request, O: Rpc_BlockText_SetColor_Response },
    { name: "BlockTextSetStyle", options: {}, I: Rpc_BlockText_SetStyle_Request, O: Rpc_BlockText_SetStyle_Response },
    { name: "BlockTextSetChecked", options: {}, I: Rpc_BlockText_SetChecked_Request, O: Rpc_BlockText_SetChecked_Response },
    { name: "BlockTextSetIcon", options: {}, I: Rpc_BlockText_SetIcon_Request, O: Rpc_BlockText_SetIcon_Response },
    { name: "BlockTextListSetColor", options: {}, I: Rpc_BlockText_ListSetColor_Request, O: Rpc_BlockText_ListSetColor_Response },
    { name: "BlockTextListSetMark", options: {}, I: Rpc_BlockText_ListSetMark_Request, O: Rpc_BlockText_ListSetMark_Response },
    { name: "BlockTextListSetStyle", options: {}, I: Rpc_BlockText_ListSetStyle_Request, O: Rpc_BlockText_ListSetStyle_Response },
    { name: "BlockTextListClearStyle", options: {}, I: Rpc_BlockText_ListClearStyle_Request, O: Rpc_BlockText_ListClearStyle_Response },
    { name: "BlockTextListClearContent", options: {}, I: Rpc_BlockText_ListClearContent_Request, O: Rpc_BlockText_ListClearContent_Response },
    { name: "BlockFileSetName", options: {}, I: Rpc_BlockFile_SetName_Request, O: Rpc_BlockFile_SetName_Response },
    { name: "BlockFileSetTargetObjectId", options: {}, I: Rpc_BlockFile_SetTargetObjectId_Request, O: Rpc_BlockFile_SetTargetObjectId_Response },
    { name: "BlockImageSetName", options: {}, I: Rpc_BlockImage_SetName_Request, O: Rpc_BlockImage_SetName_Response },
    { name: "BlockVideoSetName", options: {}, I: Rpc_BlockVideo_SetName_Request, O: Rpc_BlockVideo_SetName_Response },
    { name: "BlockFileCreateAndUpload", options: {}, I: Rpc_BlockFile_CreateAndUpload_Request, O: Rpc_BlockFile_CreateAndUpload_Response },
    { name: "BlockFileListSetStyle", options: {}, I: Rpc_BlockFile_ListSetStyle_Request, O: Rpc_BlockFile_ListSetStyle_Response },
    { name: "BlockDataviewViewCreate", options: {}, I: Rpc_BlockDataview_View_Create_Request, O: Rpc_BlockDataview_View_Create_Response },
    { name: "BlockDataviewViewDelete", options: {}, I: Rpc_BlockDataview_View_Delete_Request, O: Rpc_BlockDataview_View_Delete_Response },
    { name: "BlockDataviewViewUpdate", options: {}, I: Rpc_BlockDataview_View_Update_Request, O: Rpc_BlockDataview_View_Update_Response },
    { name: "BlockDataviewViewSetActive", options: {}, I: Rpc_BlockDataview_View_SetActive_Request, O: Rpc_BlockDataview_View_SetActive_Response },
    { name: "BlockDataviewViewSetPosition", options: {}, I: Rpc_BlockDataview_View_SetPosition_Request, O: Rpc_BlockDataview_View_SetPosition_Response },
    { name: "BlockDataviewSetSource", options: {}, I: Rpc_BlockDataview_SetSource_Request, O: Rpc_BlockDataview_SetSource_Response },
    { name: "BlockDataviewRelationSet", options: {}, I: Rpc_BlockDataview_Relation_Set_Request, O: Rpc_BlockDataview_Relation_Set_Response },
    { name: "BlockDataviewRelationAdd", options: {}, I: Rpc_BlockDataview_Relation_Add_Request, O: Rpc_BlockDataview_Relation_Add_Response },
    { name: "BlockDataviewRelationDelete", options: {}, I: Rpc_BlockDataview_Relation_Delete_Request, O: Rpc_BlockDataview_Relation_Delete_Response },
    { name: "BlockDataviewGroupOrderUpdate", options: {}, I: Rpc_BlockDataview_GroupOrder_Update_Request, O: Rpc_BlockDataview_GroupOrder_Update_Response },
    { name: "BlockDataviewObjectOrderUpdate", options: {}, I: Rpc_BlockDataview_ObjectOrder_Update_Request, O: Rpc_BlockDataview_ObjectOrder_Update_Response },
    { name: "BlockDataviewObjectOrderMove", options: {}, I: Rpc_BlockDataview_ObjectOrder_Move_Request, O: Rpc_BlockDataview_ObjectOrder_Move_Response },
    { name: "BlockDataviewCreateFromExistingObject", options: {}, I: Rpc_BlockDataview_CreateFromExistingObject_Request, O: Rpc_BlockDataview_CreateFromExistingObject_Response },
    { name: "BlockDataviewFilterAdd", options: {}, I: Rpc_BlockDataview_Filter_Add_Request, O: Rpc_BlockDataview_Filter_Add_Response },
    { name: "BlockDataviewFilterRemove", options: {}, I: Rpc_BlockDataview_Filter_Remove_Request, O: Rpc_BlockDataview_Filter_Remove_Response },
    { name: "BlockDataviewFilterReplace", options: {}, I: Rpc_BlockDataview_Filter_Replace_Request, O: Rpc_BlockDataview_Filter_Replace_Response },
    { name: "BlockDataviewFilterSort", options: {}, I: Rpc_BlockDataview_Filter_Sort_Request, O: Rpc_BlockDataview_Filter_Sort_Response },
    { name: "BlockDataviewSortAdd", options: {}, I: Rpc_BlockDataview_Sort_Add_Request, O: Rpc_BlockDataview_Sort_Add_Response },
    { name: "BlockDataviewSortRemove", options: {}, I: Rpc_BlockDataview_Sort_Remove_Request, O: Rpc_BlockDataview_Sort_Remove_Response },
    { name: "BlockDataviewSortReplace", options: {}, I: Rpc_BlockDataview_Sort_Replace_Request, O: Rpc_BlockDataview_Sort_Replace_Response },
    { name: "BlockDataviewSortSort", options: {}, I: Rpc_BlockDataview_Sort_SSort_Request, O: Rpc_BlockDataview_Sort_SSort_Response },
    { name: "BlockDataviewViewRelationAdd", options: {}, I: Rpc_BlockDataview_ViewRelation_Add_Request, O: Rpc_BlockDataview_ViewRelation_Add_Response },
    { name: "BlockDataviewViewRelationRemove", options: {}, I: Rpc_BlockDataview_ViewRelation_Remove_Request, O: Rpc_BlockDataview_ViewRelation_Remove_Response },
    { name: "BlockDataviewViewRelationReplace", options: {}, I: Rpc_BlockDataview_ViewRelation_Replace_Request, O: Rpc_BlockDataview_ViewRelation_Replace_Response },
    { name: "BlockDataviewViewRelationSort", options: {}, I: Rpc_BlockDataview_ViewRelation_Sort_Request, O: Rpc_BlockDataview_ViewRelation_Sort_Response },
    { name: "BlockTableCreate", options: {}, I: Rpc_BlockTable_Create_Request, O: Rpc_BlockTable_Create_Response },
    { name: "BlockTableExpand", options: {}, I: Rpc_BlockTable_Expand_Request, O: Rpc_BlockTable_Expand_Response },
    { name: "BlockTableRowCreate", options: {}, I: Rpc_BlockTable_RowCreate_Request, O: Rpc_BlockTable_RowCreate_Response },
    { name: "BlockTableRowDelete", options: {}, I: Rpc_BlockTable_RowDelete_Request, O: Rpc_BlockTable_RowDelete_Response },
    { name: "BlockTableRowDuplicate", options: {}, I: Rpc_BlockTable_RowDuplicate_Request, O: Rpc_BlockTable_RowDuplicate_Response },
    { name: "BlockTableRowSetHeader", options: {}, I: Rpc_BlockTable_RowSetHeader_Request, O: Rpc_BlockTable_RowSetHeader_Response },
    { name: "BlockTableColumnCreate", options: {}, I: Rpc_BlockTable_ColumnCreate_Request, O: Rpc_BlockTable_ColumnCreate_Response },
    { name: "BlockTableColumnMove", options: {}, I: Rpc_BlockTable_ColumnMove_Request, O: Rpc_BlockTable_ColumnMove_Response },
    { name: "BlockTableColumnDelete", options: {}, I: Rpc_BlockTable_ColumnDelete_Request, O: Rpc_BlockTable_ColumnDelete_Response },
    { name: "BlockTableColumnDuplicate", options: {}, I: Rpc_BlockTable_ColumnDuplicate_Request, O: Rpc_BlockTable_ColumnDuplicate_Response },
    { name: "BlockTableRowListFill", options: {}, I: Rpc_BlockTable_RowListFill_Request, O: Rpc_BlockTable_RowListFill_Response },
    { name: "BlockTableRowListClean", options: {}, I: Rpc_BlockTable_RowListClean_Request, O: Rpc_BlockTable_RowListClean_Response },
    { name: "BlockTableColumnListFill", options: {}, I: Rpc_BlockTable_ColumnListFill_Request, O: Rpc_BlockTable_ColumnListFill_Response },
    { name: "BlockTableSort", options: {}, I: Rpc_BlockTable_Sort_Request, O: Rpc_BlockTable_Sort_Response },
    { name: "BlockCreateWidget", options: {}, I: Rpc_Block_CreateWidget_Request, O: Rpc_Block_CreateWidget_Response },
    { name: "BlockWidgetSetTargetId", options: {}, I: Rpc_BlockWidget_SetTargetId_Request, O: Rpc_BlockWidget_SetTargetId_Response },
    { name: "BlockWidgetSetLayout", options: {}, I: Rpc_BlockWidget_SetLayout_Request, O: Rpc_BlockWidget_SetLayout_Response },
    { name: "BlockWidgetSetLimit", options: {}, I: Rpc_BlockWidget_SetLimit_Request, O: Rpc_BlockWidget_SetLimit_Response },
    { name: "BlockWidgetSetViewId", options: {}, I: Rpc_BlockWidget_SetViewId_Request, O: Rpc_BlockWidget_SetViewId_Response },
    { name: "BlockLinkCreateWithObject", options: {}, I: Rpc_BlockLink_CreateWithObject_Request, O: Rpc_BlockLink_CreateWithObject_Response },
    { name: "BlockLinkListSetAppearance", options: {}, I: Rpc_BlockLink_ListSetAppearance_Request, O: Rpc_BlockLink_ListSetAppearance_Response },
    { name: "BlockBookmarkFetch", options: {}, I: Rpc_BlockBookmark_Fetch_Request, O: Rpc_BlockBookmark_Fetch_Response },
    { name: "BlockBookmarkCreateAndFetch", options: {}, I: Rpc_BlockBookmark_CreateAndFetch_Request, O: Rpc_BlockBookmark_CreateAndFetch_Response },
    { name: "BlockRelationSetKey", options: {}, I: Rpc_BlockRelation_SetKey_Request, O: Rpc_BlockRelation_SetKey_Response },
    { name: "BlockRelationAdd", options: {}, I: Rpc_BlockRelation_Add_Request, O: Rpc_BlockRelation_Add_Response },
    { name: "BlockDivListSetStyle", options: {}, I: Rpc_BlockDiv_ListSetStyle_Request, O: Rpc_BlockDiv_ListSetStyle_Response },
    { name: "BlockLatexSetText", options: {}, I: Rpc_BlockLatex_SetText_Request, O: Rpc_BlockLatex_SetText_Response },
    { name: "ProcessCancel", options: {}, I: Rpc_Process_Cancel_Request, O: Rpc_Process_Cancel_Response },
    { name: "ProcessSubscribe", options: {}, I: Rpc_Process_Subscribe_Request, O: Rpc_Process_Subscribe_Response },
    { name: "ProcessUnsubscribe", options: {}, I: Rpc_Process_Unsubscribe_Request, O: Rpc_Process_Unsubscribe_Response },
    { name: "LogSend", options: {}, I: Rpc_Log_Send_Request, O: Rpc_Log_Send_Response },
    { name: "DebugStat", options: {}, I: Rpc_Debug_Stat_Request, O: Rpc_Debug_Stat_Response },
    { name: "DebugTree", options: {}, I: Rpc_Debug_Tree_Request, O: Rpc_Debug_Tree_Response },
    { name: "DebugTreeHeads", options: {}, I: Rpc_Debug_TreeHeads_Request, O: Rpc_Debug_TreeHeads_Response },
    { name: "DebugSpaceSummary", options: {}, I: Rpc_Debug_SpaceSummary_Request, O: Rpc_Debug_SpaceSummary_Response },
    { name: "DebugStackGoroutines", options: {}, I: Rpc_Debug_StackGoroutines_Request, O: Rpc_Debug_StackGoroutines_Response },
    { name: "DebugExportLocalstore", options: {}, I: Rpc_Debug_ExportLocalstore_Request, O: Rpc_Debug_ExportLocalstore_Response },
    { name: "DebugPing", options: {}, I: Rpc_Debug_Ping_Request, O: Rpc_Debug_Ping_Response },
    { name: "DebugSubscriptions", options: {}, I: Rpc_Debug_Subscriptions_Request, O: Rpc_Debug_Subscriptions_Response },
    { name: "DebugOpenedObjects", options: {}, I: Rpc_Debug_OpenedObjects_Request, O: Rpc_Debug_OpenedObjects_Response },
    { name: "DebugRunProfiler", options: {}, I: Rpc_Debug_RunProfiler_Request, O: Rpc_Debug_RunProfiler_Response },
    { name: "DebugAccountSelectTrace", options: {}, I: Rpc_Debug_AccountSelectTrace_Request, O: Rpc_Debug_AccountSelectTrace_Response },
    { name: "DebugAnystoreObjectChanges", options: {}, I: Rpc_Debug_AnystoreObjectChanges_Request, O: Rpc_Debug_AnystoreObjectChanges_Response },
    { name: "DebugNetCheck", options: {}, I: Rpc_Debug_NetCheck_Request, O: Rpc_Debug_NetCheck_Response },
    { name: "DebugExportReport", options: {}, I: Rpc_Debug_ExportReport_Request, O: Rpc_Debug_ExportReport_Response },
    { name: "DebugCleanupReport", options: {}, I: Rpc_Debug_CleanupReport_Request, O: Rpc_Debug_CleanupReport_Response },
    { name: "InitialSetParameters", options: {}, I: Rpc_Initial_SetParameters_Request, O: Rpc_Initial_SetParameters_Response },
    { name: "ListenSessionEvents", serverStreaming: true, options: {}, I: StreamRequest, O: Event },
    { name: "NotificationList", options: {}, I: Rpc_Notification_List_Request, O: Rpc_Notification_List_Response },
    { name: "NotificationReply", options: {}, I: Rpc_Notification_Reply_Request, O: Rpc_Notification_Reply_Response },
    { name: "NotificationTest", options: {}, I: Rpc_Notification_Test_Request, O: Rpc_Notification_Test_Response },
    { name: "MembershipGetStatus", options: {}, I: Rpc_Membership_GetStatus_Request, O: Rpc_Membership_GetStatus_Response },
    { name: "MembershipIsNameValid", options: {}, I: Rpc_Membership_IsNameValid_Request, O: Rpc_Membership_IsNameValid_Response },
    { name: "MembershipRegisterPaymentRequest", options: {}, I: Rpc_Membership_RegisterPaymentRequest_Request, O: Rpc_Membership_RegisterPaymentRequest_Response },
    { name: "MembershipGetPortalLinkUrl", options: {}, I: Rpc_Membership_GetPortalLinkUrl_Request, O: Rpc_Membership_GetPortalLinkUrl_Response },
    { name: "MembershipGetVerificationEmailStatus", options: {}, I: Rpc_Membership_GetVerificationEmailStatus_Request, O: Rpc_Membership_GetVerificationEmailStatus_Response },
    { name: "MembershipGetVerificationEmail", options: {}, I: Rpc_Membership_GetVerificationEmail_Request, O: Rpc_Membership_GetVerificationEmail_Response },
    { name: "MembershipVerifyEmailCode", options: {}, I: Rpc_Membership_VerifyEmailCode_Request, O: Rpc_Membership_VerifyEmailCode_Response },
    { name: "MembershipFinalize", options: {}, I: Rpc_Membership_Finalize_Request, O: Rpc_Membership_Finalize_Response },
    { name: "MembershipGetTiers", options: {}, I: Rpc_Membership_GetTiers_Request, O: Rpc_Membership_GetTiers_Response },
    { name: "MembershipVerifyAppStoreReceipt", options: {}, I: Rpc_Membership_VerifyAppStoreReceipt_Request, O: Rpc_Membership_VerifyAppStoreReceipt_Response },
    { name: "MembershipCodeGetInfo", options: {}, I: Rpc_Membership_CodeGetInfo_Request, O: Rpc_Membership_CodeGetInfo_Response },
    { name: "MembershipCodeRedeem", options: {}, I: Rpc_Membership_CodeRedeem_Request, O: Rpc_Membership_CodeRedeem_Response },
    { name: "MembershipV2GetProducts", options: {}, I: Rpc_MembershipV2_GetProducts_Request, O: Rpc_MembershipV2_GetProducts_Response },
    { name: "MembershipV2GetStatus", options: {}, I: Rpc_MembershipV2_GetStatus_Request, O: Rpc_MembershipV2_GetStatus_Response },
    { name: "MembershipV2GetPortalLink", options: {}, I: Rpc_MembershipV2_GetPortalLink_Request, O: Rpc_MembershipV2_GetPortalLink_Response },
    { name: "MembershipV2AnyNameIsValid", options: {}, I: Rpc_MembershipV2_AnyNameIsValid_Request, O: Rpc_MembershipV2_AnyNameIsValid_Response },
    { name: "MembershipV2AnyNameAllocate", options: {}, I: Rpc_MembershipV2_AnyNameAllocate_Request, O: Rpc_MembershipV2_AnyNameAllocate_Response },
    { name: "MembershipV2CartGet", options: {}, I: Rpc_MembershipV2_CartGet_Request, O: Rpc_MembershipV2_CartGet_Response },
    { name: "MembershipV2CartUpdate", options: {}, I: Rpc_MembershipV2_CartUpdate_Request, O: Rpc_MembershipV2_CartUpdate_Response },
    { name: "MembershipV2SubscribeToUpdates", options: {}, I: Rpc_MembershipV2_SubscribeToUpdates_Request, O: Rpc_MembershipV2_SubscribeToUpdates_Response },
    { name: "NameServiceUserAccountGet", options: {}, I: Rpc_NameService_UserAccount_Get_Request, O: Rpc_NameService_UserAccount_Get_Response },
    { name: "NameServiceResolveName", options: {}, I: Rpc_NameService_ResolveName_Request, O: Rpc_NameService_ResolveName_Response },
    { name: "NameServiceResolveAnyId", options: {}, I: Rpc_NameService_ResolveAnyId_Request, O: Rpc_NameService_ResolveAnyId_Response },
    { name: "BroadcastPayloadEvent", options: {}, I: Rpc_Broadcast_PayloadEvent_Request, O: Rpc_Broadcast_PayloadEvent_Response },
    { name: "DeviceSetName", options: {}, I: Rpc_Device_SetName_Request, O: Rpc_Device_SetName_Response },
    { name: "DeviceList", options: {}, I: Rpc_Device_List_Request, O: Rpc_Device_List_Response },
    { name: "DeviceNetworkStateSet", options: {}, I: Rpc_Device_NetworkState_Set_Request, O: Rpc_Device_NetworkState_Set_Response },
    { name: "ChatAddMessage", options: {}, I: Rpc_Chat_AddMessage_Request, O: Rpc_Chat_AddMessage_Response },
    { name: "ChatEditMessageContent", options: {}, I: Rpc_Chat_EditMessageContent_Request, O: Rpc_Chat_EditMessageContent_Response },
    { name: "ChatToggleMessageReaction", options: {}, I: Rpc_Chat_ToggleMessageReaction_Request, O: Rpc_Chat_ToggleMessageReaction_Response },
    { name: "ChatDeleteMessage", options: {}, I: Rpc_Chat_DeleteMessage_Request, O: Rpc_Chat_DeleteMessage_Response },
    { name: "ChatGetMessages", options: {}, I: Rpc_Chat_GetMessages_Request, O: Rpc_Chat_GetMessages_Response },
    { name: "ChatGetMessagesByIds", options: {}, I: Rpc_Chat_GetMessagesByIds_Request, O: Rpc_Chat_GetMessagesByIds_Response },
    { name: "ChatSubscribeLastMessages", options: {}, I: Rpc_Chat_SubscribeLastMessages_Request, O: Rpc_Chat_SubscribeLastMessages_Response },
    { name: "ChatUnsubscribe", options: {}, I: Rpc_Chat_Unsubscribe_Request, O: Rpc_Chat_Unsubscribe_Response },
    { name: "ChatReadMessages", options: {}, I: Rpc_Chat_ReadMessages_Request, O: Rpc_Chat_ReadMessages_Response },
    { name: "ChatUnreadMessages", options: {}, I: Rpc_Chat_Unread_Request, O: Rpc_Chat_Unread_Response },
    { name: "ChatSubscribeToMessagePreviews", options: {}, I: Rpc_Chat_SubscribeToMessagePreviews_Request, O: Rpc_Chat_SubscribeToMessagePreviews_Response },
    { name: "ChatUnsubscribeFromMessagePreviews", options: {}, I: Rpc_Chat_UnsubscribeFromMessagePreviews_Request, O: Rpc_Chat_UnsubscribeFromMessagePreviews_Response },
    { name: "ObjectChatAdd", options: {}, I: Rpc_Object_ChatAdd_Request, O: Rpc_Object_ChatAdd_Response },
    { name: "ObjectAddDiscussion", options: {}, I: Rpc_Object_DiscussionAdd_Request, O: Rpc_Object_DiscussionAdd_Response },
    { name: "ChatReadAll", options: {}, I: Rpc_Chat_ReadAll_Request, O: Rpc_Chat_ReadAll_Response },
    { name: "ChatReadReactions", options: {}, I: Rpc_Chat_ReadReactions_Request, O: Rpc_Chat_ReadReactions_Response },
    { name: "ChatSearch", options: {}, I: Rpc_Chat_Search_Request, O: Rpc_Chat_Search_Response },
    { name: "ChatSetPinnedMessages", options: {}, I: Rpc_Chat_SetPinnedMessages_Request, O: Rpc_Chat_SetPinnedMessages_Response },
    { name: "ChatGetPinnedMessages", options: {}, I: Rpc_Chat_GetPinnedMessages_Request, O: Rpc_Chat_GetPinnedMessages_Response },
    { name: "ChatAddNotificationSubscriber", options: {}, I: Rpc_Chat_AddNotificationSubscriber_Request, O: Rpc_Chat_AddNotificationSubscriber_Response },
    { name: "ChatRemoveNotificationSubscriber", options: {}, I: Rpc_Chat_RemoveNotificationSubscriber_Request, O: Rpc_Chat_RemoveNotificationSubscriber_Response },
    { name: "AIWritingTools", options: {}, I: Rpc_AI_WritingTools_Request, O: Rpc_AI_WritingTools_Response },
    { name: "AIAutofill", options: {}, I: Rpc_AI_Autofill_Request, O: Rpc_AI_Autofill_Response },
    { name: "AIListSummary", options: {}, I: Rpc_AI_ListSummary_Request, O: Rpc_AI_ListSummary_Response },
    { name: "AIObjectCreateFromUrl", options: {}, I: Rpc_AI_ObjectCreateFromUrl_Request, O: Rpc_AI_ObjectCreateFromUrl_Response },
    { name: "PushNotificationRegisterToken", options: {}, I: Rpc_PushNotification_RegisterToken_Request, O: Rpc_PushNotification_RegisterToken_Response },
    { name: "PushNotificationSetSpaceMode", options: {}, I: Rpc_PushNotification_SetSpaceMode_Request, O: Rpc_PushNotification_SetSpaceMode_Response },
    { name: "PushNotificationSetForceModeIds", options: {}, I: Rpc_PushNotification_SetForceModeIds_Request, O: Rpc_PushNotification_SetForceModeIds_Response },
    { name: "PushNotificationResetIds", options: {}, I: Rpc_PushNotification_ResetIds_Request, O: Rpc_PushNotification_ResetIds_Response }
]);
