// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "pb/protos/snapshot.proto" (package "anytype", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Block_Content_Widget_Layout } from "../../pkg/lib/pb/model/protos/models";
import { Change_Snapshot } from "./changes";
import { SmartBlockType } from "../../pkg/lib/pb/model/protos/models";
/**
 * @generated from protobuf message anytype.SnapshotWithType
 */
export interface SnapshotWithType {
    /**
     * @generated from protobuf field: anytype.model.SmartBlockType sbType = 1
     */
    sbType: SmartBlockType;
    /**
     * @generated from protobuf field: anytype.Change.Snapshot snapshot = 2
     */
    snapshot?: Change_Snapshot;
}
/**
 * @generated from protobuf message anytype.Profile
 */
export interface Profile {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string avatar = 2
     */
    avatar: string;
    /**
     * @generated from protobuf field: string address = 4
     */
    address: string;
    /**
     * @generated from protobuf field: string spaceDashboardId = 5
     */
    spaceDashboardId: string; // aka homepage
    /**
     * @generated from protobuf field: string profileId = 6
     */
    profileId: string;
    /**
     * @generated from protobuf field: string analyticsId = 7
     */
    analyticsId: string;
    /**
     * @generated from protobuf field: string startingPage = 8
     */
    startingPage: string; // deprecated
    /**
     * @generated from protobuf field: repeated anytype.WidgetBlock widgets = 9
     */
    widgets: WidgetBlock[];
}
/**
 * @generated from protobuf message anytype.WidgetBlock
 */
export interface WidgetBlock {
    /**
     * @generated from protobuf field: anytype.model.Block.Content.Widget.Layout layout = 1
     */
    layout: Block_Content_Widget_Layout;
    /**
     * @generated from protobuf field: string targetObjectId = 2
     */
    targetObjectId: string;
    /**
     * @generated from protobuf field: int32 objectLimit = 3
     */
    objectLimit: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class SnapshotWithType$Type extends MessageType<SnapshotWithType> {
    constructor() {
        super("anytype.SnapshotWithType", [
            { no: 1, name: "sbType", kind: "enum", T: () => ["anytype.model.SmartBlockType", SmartBlockType] },
            { no: 2, name: "snapshot", kind: "message", T: () => Change_Snapshot }
        ]);
    }
    create(value?: PartialMessage<SnapshotWithType>): SnapshotWithType {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sbType = 0;
        if (value !== undefined)
            reflectionMergePartial<SnapshotWithType>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SnapshotWithType): SnapshotWithType {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* anytype.model.SmartBlockType sbType */ 1:
                    message.sbType = reader.int32();
                    break;
                case /* anytype.Change.Snapshot snapshot */ 2:
                    message.snapshot = Change_Snapshot.internalBinaryRead(reader, reader.uint32(), options, message.snapshot);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SnapshotWithType, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* anytype.model.SmartBlockType sbType = 1; */
        if (message.sbType !== 0)
            writer.tag(1, WireType.Varint).int32(message.sbType);
        /* anytype.Change.Snapshot snapshot = 2; */
        if (message.snapshot)
            Change_Snapshot.internalBinaryWrite(message.snapshot, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.SnapshotWithType
 */
export const SnapshotWithType = new SnapshotWithType$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Profile$Type extends MessageType<Profile> {
    constructor() {
        super("anytype.Profile", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "avatar", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "spaceDashboardId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "profileId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "analyticsId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "startingPage", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "widgets", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WidgetBlock }
        ]);
    }
    create(value?: PartialMessage<Profile>): Profile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.avatar = "";
        message.address = "";
        message.spaceDashboardId = "";
        message.profileId = "";
        message.analyticsId = "";
        message.startingPage = "";
        message.widgets = [];
        if (value !== undefined)
            reflectionMergePartial<Profile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Profile): Profile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string avatar */ 2:
                    message.avatar = reader.string();
                    break;
                case /* string address */ 4:
                    message.address = reader.string();
                    break;
                case /* string spaceDashboardId */ 5:
                    message.spaceDashboardId = reader.string();
                    break;
                case /* string profileId */ 6:
                    message.profileId = reader.string();
                    break;
                case /* string analyticsId */ 7:
                    message.analyticsId = reader.string();
                    break;
                case /* string startingPage */ 8:
                    message.startingPage = reader.string();
                    break;
                case /* repeated anytype.WidgetBlock widgets */ 9:
                    message.widgets.push(WidgetBlock.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Profile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string avatar = 2; */
        if (message.avatar !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.avatar);
        /* string address = 4; */
        if (message.address !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.address);
        /* string spaceDashboardId = 5; */
        if (message.spaceDashboardId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.spaceDashboardId);
        /* string profileId = 6; */
        if (message.profileId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.profileId);
        /* string analyticsId = 7; */
        if (message.analyticsId !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.analyticsId);
        /* string startingPage = 8; */
        if (message.startingPage !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.startingPage);
        /* repeated anytype.WidgetBlock widgets = 9; */
        for (let i = 0; i < message.widgets.length; i++)
            WidgetBlock.internalBinaryWrite(message.widgets[i], writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.Profile
 */
export const Profile = new Profile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WidgetBlock$Type extends MessageType<WidgetBlock> {
    constructor() {
        super("anytype.WidgetBlock", [
            { no: 1, name: "layout", kind: "enum", T: () => ["anytype.model.Block.Content.Widget.Layout", Block_Content_Widget_Layout] },
            { no: 2, name: "targetObjectId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "objectLimit", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<WidgetBlock>): WidgetBlock {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.layout = 0;
        message.targetObjectId = "";
        message.objectLimit = 0;
        if (value !== undefined)
            reflectionMergePartial<WidgetBlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WidgetBlock): WidgetBlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* anytype.model.Block.Content.Widget.Layout layout */ 1:
                    message.layout = reader.int32();
                    break;
                case /* string targetObjectId */ 2:
                    message.targetObjectId = reader.string();
                    break;
                case /* int32 objectLimit */ 3:
                    message.objectLimit = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WidgetBlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* anytype.model.Block.Content.Widget.Layout layout = 1; */
        if (message.layout !== 0)
            writer.tag(1, WireType.Varint).int32(message.layout);
        /* string targetObjectId = 2; */
        if (message.targetObjectId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.targetObjectId);
        /* int32 objectLimit = 3; */
        if (message.objectLimit !== 0)
            writer.tag(3, WireType.Varint).int32(message.objectLimit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message anytype.WidgetBlock
 */
export const WidgetBlock = new WidgetBlock$Type();
